### PR TITLE
Rollup fcls for MCP2021C testing

### PR DESCRIPTION
**Pull request by henrylay97**
This PR adds the fcls required to test rollup being turned off, and further turning off mcreco as discussed in #230.

### CODE REVIEW

**Comment by pgreen135** [comment]
are these additional fhicls sufficient for production testing? there are various other workflows that inherit the standard_g4 fhicls that wouldn't pick this up -- e.g. the dirt workflows, PDS ones, commissioning ones

**Comment by henrylay97** [comment]
This is a really good point, sorry! Has anyone got a list of the fcls intended to be used in this production?

**Comment by pgreen135** [comment]
discussing with @henrylay97, the plan is to merge this into today's release as is to enable testing of the core workflows on Monday. Then next week there will be a followup patch with the full set of configurations pending the results from the testing / input from US people (some workflows may need MCReco etc.).

**Comment by jzennamo** [comment]
Thank you, this was exactly what we needed, I have started testing now and I can work on getting patch fcls in place based on these!

**Pull request merged**
