### PR TITLE
Pandora 3D Mop up

### PR DESCRIPTION
**Pull request by etyley**
This PR includes 2 changes to Pandora for SBND:
- Rerun the 3D hit creation within the recursive shower mop up
- Enable shower hierarchy mop up

Details of performance changes can be seen in [DocDB #21900](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=21900)

This PR relies on https://github.com/PandoraPFA/LArContent/pull/175 and should not be merged until this is included upstream

### CODE REVIEW

**Review by absolution1 — APPROVED** [review]
Nice clean additions to the XML and it seems pretty clear what's going on.
Nice work!

**Comment by absolution1** [comment]
Ed's last commit added a line of comments explaining why the PFO characterisation is rerun, so there's nothing to re-review here.  This PR can go in as soon as the respective LArContent PR has gone into upstream LArSoft.

**Comment by etyley** [comment]
There is now a pull request to LArSoft to include this in the next release: https://github.com/LArSoft/larpandoracontent/pull/27

**Comment by pgreen135** [comment]
trigger build LArSoft/larpandoracontent#27

**Comment by pgreen135** [comment]
@etyley there are some product size differences in the e20:prof nucosmics_reco2 CI test -- I presume these are expected given the Pandora changes, but could you double-check? Thanks! 

https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/6535&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof

**Comment by etyley** [comment]
Yeah, those changes are expected.

**Pull request merged**
