### PR TITLE
created PMT Hardware Trigger Simulation in Trigger folder and modifie…

### PR DESCRIPTION
**Pull request by eyandel**
…d HitDumper module to analyze it

This is a module to simulate the PMT hardware trigger on simulated data. It takes a largeant file with optical detectors waveforms and produces a vector whose index is time within the trigger (beam) window and content is number of PMT pairs passing the trigger threshold.
 
More information can be found at: https://sbnsoftware.github.io/sbndcode_wiki/SBND_Trigger and sbn-docdb: 23922
 
The trigger logic implemented currently:
 - Turn raw OpDetWaveforms (in ADC) into binary waveforms (0=not above threshold, 1=above threshold)
 - Downsample binary waveform by 4 (simulate 2ns rate, hardware reads every 8ns)
 - Pair waveforms -> combine 2 downsampled waveforms based on parameters set in fhicl files
 - Extend wavelength when a rising edge is seen
 - Count the number of paired waveforms above threshold for various times within the trigger window

Input:
 - output from OpDetSim module (in particular, OpDetWaveforms)

Output:
 - std::vector<sbnd::comm::pmtTrigger> > : PMT trigger array

fhicl: run_pmttriggerproducer.fcl

### CODE REVIEW

**Review by mstancar — APPROVED** [review]

**Comment by pgreen135** [comment]
@eyandel is this the code you were presenting yesterday? Could you add a bit more detailed description of what each part is doing (just a few bullet points and a link to that talk, mostly just for the sake of having a record). 

I've had a quick look through, not a detailed review -- I notice there is quite a lot of commented out bits of code, and some big blocks of white space in places, could you go through and tidy this up? (unless this commented out code is there for a reason).

**Comment by pgreen135** [comment]
@eyandel thanks for adding the description / links to documentation (I've added this to the PR description too for clarity) and for tidying up the code

**Comment by pgreen135** [comment]
trigger build

**Comment by pgreen135** [comment]
trigger build SBNSoftware/sbnobj#32

**Comment by pgreen135** [comment]
@eyandel looks like there is a c7 failure due to an unused variable

**Comment by pgreen135** [comment]
trigger build SBNSoftware/sbnobj#32

**Review by pgreen135 — APPROVED** [review]

**Pull request merged**
