### PR TITLE
enable neutrino time of flight for PR#320

### PR DESCRIPTION
**Pull request by VCLanNguyen**
Also see #325 and #326.

### CODE REVIEW

**Comment by RachelCoackley** [comment]
Ref files are now updated! Will do the normal tests and then the seq tests 😊

**Comment by RachelCoackley** [comment]
Quick tests look good to me, only difference is in fcl_checks_sbndcode (other warnings are just cpu usage) where it has "AddGenieVtxTime: true" being added. I think this is fine but this is the link if you want to check it yourself! https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2023/03/21/stdout%23UEfHZjv.log

**Comment by VCLanNguyen** [comment]
So I checked the [nucosmics_caf_seq_test_sbndcode](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/test_details?build_id=sbnd_ci/11518&platform=Linux%203.10.0-1160.81.1.el7.x86_64&buildtype=slf7%20e20:prof&phase=ci_tests&test=nucosmics_caf_seq_test_sbndcode)  and I can see that the mc time difference is ~0.367 us, as expected. So the AddGenieVtxTime is propagated through correctly

5285:   rec.mc.nu[0].prim[0].genT differs: 0.891114354133606 vs 1.2579537630081177
5286:   rec.mc.nu[0].prim[1].endT differs: 0.8929833769798279 vs 1.2598228454589844
5287:   rec.mc.nu[0].prim[1].genT differs: 0.891114354133606 vs 1.2579537630081177
5288:   rec.mc.nu[0].prim[1].startT differs: 0.892983078956604 vs 1.2598224878311157
5289:   rec.mc.nu[0].prim[2].endT differs: 0.8925550580024719 vs 1.2593945264816284
5290:   rec.mc.nu[0].prim[2].genT differs: 0.891114354133606 vs 1.2579537630081177
5291:   rec.mc.nu[0].prim[2].startT differs: 0.8917343616485596 vs 1.2585737705230713
5292:   rec.mc.nu[0].time differs: 0.891114354133606 vs 1.2579537630081177

**Comment by VCLanNguyen** [comment]
@henrylay97 @fjnicolas Can you guys give me opinion on the tpc, crt and pds reco results from [nucosmics_caf_seq_test_sbndcode](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/test_details?build_id=sbnd_ci/11518&platform=Linux%203.10.0-1160.81.1.el7.x86_64&buildtype=slf7%20e20:prof&phase=ci_tests&test=nucosmics_caf_seq_test_sbndcode)

For example, some TPC reco comparison for starting position and the changes don't look significant to me.

3069:   rec.slc[0].reco.pfp[0].trk.start.x differs: -201.04141235351562 vs -201.0535430908203
3070:   rec.slc[0].reco.pfp[0].trk.start.y differs: 98.78057098388672 vs 98.88212585449219
3071:   rec.slc[0].reco.pfp[0].trk.start.z differs: 427.26544189453125 vs 427.203369140625

3019:   rec.slc[0].reco.pfp[0].shw.start.x differs: -201.04783630371094 vs -201.0535430908203
3020:   rec.slc[0].reco.pfp[0].shw.start.y differs: 98.77791595458984 vs 98.88212585449219
3021:   rec.slc[0].reco.pfp[0].shw.start.z differs: 427.2682189941406 vs 427.203369140625

CRT reco also looks alright and the only difference is the time variable:

4184:   rec.crt_hits[119].pe differs: 211.8830108642578 vs 211.81378173828125
4185:   rec.crt_hits[119].position.x differs: 390.8655090332031 vs 390.84185791015625
4186:   rec.crt_hits[119].position.z differs: 738.6307373046875 vs 738.6600952148438
4187:   rec.crt_hits[119].position_err.x differs: 1.5889770984649658 vs 1.591691493988037
4188:   rec.crt_hits[119].position_err.z differs: 1.7438286542892456 vs 1.7463270425796509
4189:   rec.crt_hits[119].t0 differs: 0.24300000071525574 vs 0.621999979019165
4190:   rec.crt_hits[119].t1 differs: 0.24300000071525574 vs 0.621999979019165
4191:   rec.crt_hits[119].time differs: 0.24300000071525574 vs 0.621999979019165


However, it looks quite drastic difference on PDS reco, which is also what we expect(?) 
4214:   rec.slc[0].fmatch.lightCenter.x differs: -187.37335205078125 vs -185.02081298828125
4215:   rec.slc[0].fmatch.lightCenter.y differs: 94.2714614868164 vs 55.66156768798828
4216:   rec.slc[0].fmatch.lightCenter.z differs: 450.6829833984375 vs 423.78704833984375
4217:   rec.slc[0].fmatch.lightPE differs: 11.382980346679688 vs 12.720499992370605
4218:   rec.slc[0].fmatch.lightWidth.x differs: 0.190476194024086 vs 0.3461538553237915
4219:   rec.slc[0].fmatch.lightWidth.y differs: 64.62601470947266 vs 67.8462905883789
4220:   rec.slc[0].fmatch.lightWidth.z differs: 34.92191696166992 vs 61.74773406982422
4221:   rec.slc[0].fmatch.score differs: 36.53852462768555 vs 35.9135856628418

**Comment by henrylay97** [comment]
@chilge is it going to be possible to use the full validation system on a reasonable time scale for this PR? Would be a great reassurance to see the reconstruction plots unchanged.

**Comment by fjnicolas** [comment]
Hi! Looks good to to me from a PDS point of view. The time related variables for the nu matches are shifted ~367 ns as well. See eg:
- 5459:   rec.slc[1].fmatch.time differs: 1.0449999570846558 vs 1.411000013351 4404
- 9045:   rec.slc[1].fmatch_a.time differs: 1.1510000228881836 vs 1.5190000534057617

The particular example pointed out by Lan seems to be a very low energy flash (4217: rec.slc[0].fmatch.lightPE differs: 11.382980346679688 vs 12.720499992370605) so I'm not surprised about the larger changes in the Y and Z barycenters values. Changes in the flash matching reco variables for the other events look sensitive.

**Review by marcodeltutto — APPROVED** [review]
Looks good to me and I am happy to approve it. Thanks, @VCLanNguyen!

@chilge, if you think we can spin the full validation system, that would be great. Otherwise, I am happy with this PR being merged.

**Comment by chilge** [comment]
@henrylay97 @marcodeltutto  sorry for the delay. I haven't had any time to make the repairs and generate the new validation inputs/references. will make this a priority for next week.

**Comment by henrylay97** [comment]
Not at all, thanks Chris!

**Comment by chilge** [comment]
@fjnicolas making progress with lots of help from Vito. running some tests now. which validation workflow do you intend to use? all of them? pds only? 

what version of sbndcode would you like to compare against? it looks like the validation workflows are no longer synced in terms of version. for PDS, I see references for v09_51_00. Most other workflows only go up to v09_37_01_03p01. If I need to generate new inputs and references, this will take at least a day.

**Comment by fjnicolas** [comment]
Thanks for the heads up @chilge and all the work getting the CI up to date. Since all reviewers seem to be ok with the result of the sequential test, I will merge it now and cut the new release.

There have been major changes in both PDS/TPC reco since the references tags you mentioned. It'd be great to have new refs for all the different workflows. I'd suggest to start with `v09_69_01` or the upcoming `v09_71_00` (we can continue the discussion offline).

**Pull request merged**
