### PR TITLE
Reworked PDS boxes and X-ARAPUCAS

### PR DESCRIPTION
**Pull request by gustavogx**
Reworked PDS boxes and X-ARAPUCAS to use rotations in a way to NOT confuse the Light Simulation

### CODE REVIEW

**Comment by pgreen135** [comment]
@ikatza @rodralva could you repeat your test with the muons to double-check that this resolves the issue?

**Comment by gustavogx** [comment]
A comment: I used the information provided by @ikatza in the other issue (#123):

"The radius of the dome for the PMTs is taken from a fcl file, which hasn't changed. As far as I can tell their positions are OK."

And applied rotations to the PMT only. This is unavoidable since cylinder solids can only be generated with its symmetry axis in the Z direction. But, since Iker clarified that the PMTs info is taken from the fcl file, it shouldn't be a problem.

**Comment by ikatza** [comment]
Hi, these changes don't work. When printing the XARAPUCA dimensions I get:

```
Length:0.2, Height:20.6
```

I suppose larsoft expects to get an `x, y, z` vector in that order. And the latest changes swapped `z` to be in the first entry, and `x` to be on the last.

**Comment by gustavogx** [comment]
I don't believe it. The coordinates should be read by the parser in an
order-independent fashion. What is going on here?

I will change the values instead. Give me some time.
G.

Em sex., 9 de jul. de 2021 às 13:06, Iker de Icaza ***@***.***>
escreveu:

**Comment by gustavogx** [comment]
I just pushed a fix. Could you try it out @ikatza  ?

**Comment by ikatza** [comment]
Yes! 

Fixed:
```
Length:7.6, Height:20.6
```

**Comment by pgreen135** [comment]
There will be a new sbndcode tag on Monday, I will include this. Thanks everyone for finding and fixing this so promptly!

**Comment by rodralva** [comment]
Everything seems fine
image
It's very preliminary, but it seems that there's a bit less light arriving at detectors with the new geometry (altough this was just a small 1k event sample). [This is the fcl cofiguration](https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/JobConfigurations/standard/gen/genie/other_flux_config/flux_configf/prodgenie_nu_singleinteraction_tpc_gsimple-configf-v1.fcl) for the muons I've been using.

**Pull request merged**
