### PR TITLE
Feature/lkashur geo wires2

### PR DESCRIPTION
**Pull request by lkashur**
## Description 
Update no. of collection plane wires in simulation to 1670.   This is a slight change to the gdml (and base gdml), see sbnd_v02_02.gdml.  Then mask the central 6 wires to account for the gap between APAs, and one wire on each half APA to account for wire combs, bringing us to the correct number of collection plane wires (1662).  These changes are incorporated in sbndcode/Utilities/badchannels_sbnd.fcl and sbndcode/Utilities/channelstatus_sbnd.fcl.

maskedcolwires

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by marcodeltutto** [comment]
Thank you, @lkashur!

@tomjunk @yangtj207 This PR changes the number of collection plane wires. Could you please take a look? 
As Lane wrote above, there are now 1670 wires on the collection planes. When saving data, the 6 wires in the middle should be skipped. 
This PR keeps the number of induction wires to 1984 but removes all the "bad" channels in these planes so that we can use all the 1984 channels for both simulation and data.

@absolution1 The bad channels from data (PR #487) should be updated. Is this something you could help with?

**Comment by bear-is-asleep** [comment]
Does this fix issue #438 @lkashur ? If so we can link to this issue under `Development` and close the issue.

**Comment by bear-is-asleep** [comment]
> Does this fix issue #438 @lkashur ? If so we can link to this issue under `Development` and close the issue.

Oh I see @marcodeltutto has done this already, thanks for being on top of it!

**Comment by bear-is-asleep** [comment]
Are we safe to close this? I'm under the impression that PR #499 covers this now.

**Comment by marcodeltutto** [comment]
Hi @bear-is-asleep, yes, this should be safe to close, thanks!

**Pull request closed without merging**
