### PR TITLE
Feature/lkashur crt colwires gdml fix

### PR DESCRIPTION
**Pull request by lkashur**
## Description 
This PR updates SBND's simulated geometry, including changes to the CRT (#498) and TPC collection plane wires (#496).  Also update are the "bad channels" list (sbndcode/Utilities/badchannels_sbnd.fcl and sbndcode/Utilities/channelstatus_sbnd.fcl) to go along with the collection plane wires fix. 

Dependent on all PRs in project [34](https://github.com/orgs/SBNSoftware/projects/34) to be ready, since fcl tables are affected by new channel mapping IDs.

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [x] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Relevant PR links (optional)
Does this PR require merging another PR in a different repository (such as sbnanobj/sbnobj etc.)?

### Link(s) to docdb describing changes (optional)
Is there a docdb describing the issue this solves or the feature added?

### CODE REVIEW

**Comment by lkashur** [comment]
Just ended up making a new branch to include both our changes @henrylay97.  Could you verify that everything CRT-related made it in here?

**Comment by bear-is-asleep** [comment]
Is this going to change any channel numbers that need to be considered in PRs like #497 and #487?

**Comment by henrylay97** [comment]
Yep, this looks good to me! Thanks @lkashur!

**Review by henrylay97 — APPROVED** [review]

**Comment by marcodeltutto** [comment]
Thank you again, @lkashur! And also for merging the CRT work!

@tomjunk @yangtj207 This PR changes the number of collection plane wires. I am tagging you again as this replaces PR #496. 😄 Could you please take a look?
As Lane wrote above, there are now 1670 wires on the collection planes. When saving data, the 6 wires in the middle should be skipped.
This PR keeps the number of induction wires to 1984 but removes all the "bad" channels in these planes so that we can use all the 1984 channels for both simulation and data.

@absolution1 The bad channels from data (PR https://github.com/SBNSoftware/sbndcode/pull/487) should be updated. Is this something you could help with?

**Comment by tomjunk** [comment]
Yes, will take a look, though Tingjun and I are on vacation this week as Fermilab requires it.

**Comment by tomjunk** [comment]
Dom is also out until the end of August.

**Comment by tomjunk** [comment]
I checked the wire dumps -- so far the number of channels per plane looks as expected.  I recomputed the bad channel numbers and they agree with Haiwang's update of the bad channel list on the last page of SBN-doc-37116-v2.

**Comment by tomjunk** [comment]
I updated the channel map text file (now sbndcode/ChannelMaps/TPC/SBNDTPCChannelMap_v2.txt, keeping the old one in case someone wants to use the old GDML) and updated the fcl config to point to it.  I redecoded a file from run 15040 using the new channel map and ran the larsoft event display with evd_sbnd_data.fcl.  I searched for an event which has a steep track that crosses the APA gap in Y on the west and made an event display, see below.

n.b.  With the other commits in this PR, the default GDML one is now the v2.2 which is great.  I ran the MC gen and sim (though I had to use the legacy detsim without CRT as WireCell seemed to not initialize when I tried it), and noticed each time the GDML was loaded, the V2.2 one was chosen, and that was true with the event display too.  This is great, but reading in an old decoded data file with the new geometry will show errors in the event display or reco.  The TPC decoder does not actually use the geometry, and so existing decoded files, such as those in the commissioning area in dCachek, will not trigger LArSoft's check on consistency of the geometry.  They will still read in, but the channel numbering will not be right for the new geometry.  Instead, one ought to re-decode the raw data with the new channel map.
evd twq-proj 15040 319

**Comment by tomjunk** [comment]
I also updated SBN-doc-35006-v1 with a new cartoon and wire end dump text file and root file.

**Comment by tomjunk** [comment]
It looks like the decoded files in the commissioning area in dCache indeed do have the geometry information in their configuration.  So while they still need to be re-decoded in order to use the data with the v2.2 geometry, attempting to read in one that was decoded with the v2.0 geometry into a job using the v2.2 geometry ought to generate an exception from the geometry configuration writer.

**Comment by tomjunk** [comment]
A separate problem I had was the legacy detsim fcl couldn't find crtslimmer_sbnd.fcl

lar -c legacy_detsim_sbnd.fcl g4.root
Failed to parse the configuration file 'legacy_detsim_sbnd.fcl' with exception
---- search_path BEGIN
  Can't find file "crtslimmer_sbnd.fcl"
---- search_path END

Art has completed and will exit with status 90.

**Comment by tomjunk** [comment]
It would be good to see if (U, V, Y) hit triplets match better now, now that the Y hit locations are ±9 mm displaced.

**Comment by marcodeltutto** [comment]
@tomjunk can you share the path to your redecoded file from run 15040?

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by bear-is-asleep** [comment]
Hi @tomjunk @marcodeltutto @yangtj207 @dombarker30 , can one of you review/approve the PR? Thanks!

**Comment by marcodeltutto** [comment]
I would like to have the following approvals on this PR:
- @tomjunk for the decoder part 
- either @yangtj207 or @dombarker30 for the reconstruction side

**Review by tomjunk — APPROVED** [review]
Yes, I approve for the decoder/channel map and the new TPC channel numbering and locations in the v2.2 GDML file.

**Comment by tomjunk** [comment]
And I can answer my own question about whether points match up better in the three views with the new geometry, and indeed they do.  Here is the same track, which crosses the APA gap, in the old geometry and old channel map, and again with the new geometry and new channel map.  The magenta stars come from the LArSoft event display's shift-click 3D space point finder, with the two input points being Induction 1 and Induction 2 (U and V), and the predicted point is in collection.  There is a 3-wire offset, as expected, and the new geometry is clearly a better match.  The track may actually end partway through the argon volume observed by any given wire, so the points still don't match exactly.

trackend_oldgeo
starpts_trackend_newgeo

**Comment by tomjunk** [comment]
And here's a randomly-selected track endpoint (I think the track goes through the APA), in the old and new geo.  The 3 wire spacings help a lot.
example2_newgeo
example2_oldgeo

**Review by yangtj207 — APPROVED** [review]
Looks good to me.

**Review by marcodeltutto — APPROVED** [review]
Thanks!

**Pull request merged**
