### PR TITLE
Fix CI from reco refactoring

### PR DESCRIPTION
**Pull request by bear-is-asleep**
Reco fcls were refactored in [PR460](https://github.com/SBNSoftware/sbndcode/pull/460), but the CI silently failed. This PR aims to fix any residual failures in the CI.

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbncode@v09_90_00

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbncode@v09_90_00

**Review by absolution1 — APPROVED** [review]
Your changes look good to me @bear-is-asleep

**Review by henrylay97 — COMMENTED** [review]
Looks good to me other than one query @absolution1. Are we deliberately keeping the commissioning fcl called: `reco1_sce_comm.fcl` ? In the new paradigm it inherits (two steps up the chain) from `standard_reco1_sbnd.fcl`. Should we just call it `reco1_comm.fcl` ?

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbncode@v09_90_00

**Pull request merged**
