### PR TITLE
Update wcls-sim-drift-depoflux-nf-sp.jsonnet

### PR DESCRIPTION
**Pull request by bear-is-asleep**
This config does something weird to the energy deposits, making the total energy deposited much greater than the total energy of the particle. Removing this produces much more reasonable values, i.e. values always less than the total energy.

### CODE REVIEW

**Review by lynnt20 — APPROVED** [review]
yup...

**Comment by fjnicolas** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_89_01 SBNSoftware/sbncode@v09_89_01

**Comment by fjnicolas** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_89_01 SBNSoftware/sbncode@v09_89_01

**Comment by bear-is-asleep** [comment]
Lynn and I tested and validated it worked with the WC workflow. The CI is complaining about a sbncode version mismatch which is unrelated and to be resolved.

**Pull request merged**
