### PR TITLE
Update CI cpu and memory limits

### PR DESCRIPTION
**Pull request by bear-is-asleep**
## Description 
Update memory and CPU limits for CI warnings

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [na] Linked any relevant issues under `Developement`
- [na] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [na] Does this affect the standard workflow?

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 SBNSoftware/sbncode@56dc342f SBNSoftware/sbnobj@a4b93770 SBNSoftware/sbndcode@e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 https://github.com/SBNSoftware/sbncode/commit/56dc342f https://github.com/SBNSoftware/sbnobj/commit/a4b93770 https://github.com/SBNSoftware/sbndcode/commit/e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Review by henrylay97 — APPROVED** [review]
These look sensible to me based on our chat yesterday @bear-is-asleep. We should rack our brains on things that might have contributed to this over the last few months.

The failure to build the CI is related to the pre-emptive merge of SBNSoftware/sbnobj#113. If you want to test without this you'll need a commit from sbnobj before this merge.

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 https://github.com/SBNSoftware/sbncode/commit/56dc342f https://github.com/SBNSoftware/sbnobj/commit/c42c62f https://github.com/SBNSoftware/sbndcode/commit/e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 https://github.com/SBNSoftware/sbncode/commit/56dc342f https://github.com/SBNSoftware/sbnobj/commit/e90142b04ecec2183209aabf6554a41962853056 https://github.com/SBNSoftware/sbndcode/commit/e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 https://github.com/SBNSoftware/sbncode/commit/56dc342f https://github.com/SBNSoftware/sbnobj/commit/df81a8a https://github.com/SBNSoftware/sbndcode/commit/e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by henrylay97** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 SBNSoftware/sbncode@ 56dc342f SBNSoftware/sbnobj@ df81a8a SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by henrylay97** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 SBNSoftware/sbncode@ 56dc342f SBNSoftware/sbnobj@ df81a8a SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Pull request merged**
