### PR TITLE
Fhicl files folder to run MeVPrtl generator (modules live in sbncode)

### PR DESCRIPTION
**Pull request by VCLanNguyen**
Basic fcl files set up to run the MeVPrtl generator for Heavy Neutral Lepton production

### CODE REVIEW

**Review by rodralva — APPROVED** [review]
Seems good to me!

**Comment by fjnicolas** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by fjnicolas** [comment]
Hi @VCLanNguyen, there are some missing headers in some of the the `set_*.fcl` fhicls, can you have a look? thanks!

**Comment by VCLanNguyen** [comment]
trigger build

**Comment by VCLanNguyen** [comment]
trigger build

**Comment by VCLanNguyen** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_64_01

**Comment by fjnicolas** [comment]
trigger build

**Pull request merged**
