### PR TITLE
Add calibration ntuples caloskimmer into the standard reco2 fcl

### PR DESCRIPTION
**Pull request by VCLanNguyen**
Add caloskimmer, that runs uncalibrated calorimetry then creates ntuples for calibration, into the standard sbnd reco2 file. The caloskimmer is located sbncode. This is intended for October production.

Also edit the pandoraCalo to use Gnocchi module.

### CODE REVIEW

**Comment by pgreen135** [comment]
trigger build

**Comment by pgreen135** [comment]
CI test warnings make sense - related to removal of opt0finder and addition of caloskimCalorimetry data products

**Comment by pgreen135** [comment]
following discussion in PAT meeting, awaiting validation plots from @VCLanNguyen before merging

**Comment by VCLanNguyen** [comment]
This sbndcode PR needs be merged together as the one below from sbncode:
[https://github.com/SBNSoftware/sbncode/pull/173]
The caloskimmer in the standard reco2 requires the fcl in the sbn calibration.

**Review by pgreen135 — APPROVED** [review]

**Pull request merged**
