### PR TITLE
added lines to track and shower creation blocks to run the creations …

### PR DESCRIPTION
**Pull request by rhowell42**
…over all PFOs

Matched to the similar PR here for icaruscode https://github.com/SBNSoftware/icaruscode/pull/424

also matched to the following PRs in sbnanaobj, sbnana, and sbncode

https://github.com/SBNSoftware/sbnanaobj/pull/66
https://github.com/SBNSoftware/sbnana/tree/feature/rh_testCAF
https://github.com/SBNSoftware/sbncode/tree/feature/rh_allPFOs

### CODE REVIEW

**Review by etyley — APPROVED** [review]
Looks good to me, I guess the CI will throw up a whole bunch of warnings that verify this is working properly

**Comment by absolution1** [comment]
Hello.
This change will need testing with the full validation system, as I'd expect this may cause some of those checks to break too.  I am paging @henrylay97 so that he is aware.

I assume this is already the case, but these merges between sbndcode/icaruscode/other sbn packages should be coordinated to merge at the same time (particularly between sbndcode and icaruscode).

**Comment by henrylay97** [comment]
Hiya! Yeah it looks like this whole group of PRs will need quite a significant testing suite. I'll start thinking about this today, thanks for the ping.

**Comment by absolution1** [comment]
The Validation system is the closest automated routine we've got to a standard analysis.  So, it would be extremely useful to keep notes on what needs to be changed in the validation workflow/scripts to accommodate these changes.  Then those changes should be advertised, to give analysers a heads up about the kinds of things they should expect to change in their own analyses.

**Comment by fjnicolas** [comment]
trigger build

**Comment by fjnicolas** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbn*@release/SBN2022B

**Comment by fjnicolas** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbndaq-artdaq-core@offline SBNSoftware/sbn*@release/SBN2022B

**Comment by fjnicolas** [comment]
Hi @rhowell42, planning to finally include this in the next release to match the equivalent SBN PRs. Can you please comment on the CI warnings/confirm they look sensible? I see there is an increment in the number of reco tracks, shouldn't we expect also an increment in the number of showers??

Pinging also @absolution1, @etyley, @henrylay97 so they are aware

**Comment by rhowell42** [comment]
I added some  more lines in that fhicl file @fjnicolas ; I'm unfamiliar with SBND's simulation procedure, so please let me know if I did something incorrect.

**Comment by fjnicolas** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_63_00 SBNSoftware/sbndaq-artdaq-core@offline SBNSoftware/sbn*@release/SBN2022B

**Comment by henrylay97** [comment]
Thanks for the alert @fjnicolas 

@rhowell42 thanks for amending, especially on an unfamiliar experiment. Can I request that you remove the "new line 128" from your most recent commit? "New line 71" should cover it as the incremental table inherits after this line. It will just reduce the points of maintenance for us. Thanks!

**Comment by rhowell42** [comment]
Done, this should be good to go then. Thanks Henry!

**Comment by fjnicolas** [comment]
thanks @rhowell42 @henrylay97! CI looks good to me (different product sizes and caf outputs expected).

**Comment by henrylay97** [comment]
I fully agree, looks good to go from my point of view. I can run the sequential tests as well if you're doing the release tomorrow? If today, no worries.

**Comment by henrylay97** [comment]
Awesome, will do!

**Comment by henrylay97** [comment]
Had some problems with the overnight build but re-ran this morning and all is good. 

https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/10850&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof

We see downstream implications and checking the caf files offline I can see the relevant variables being filled.

**Comment by fjnicolas** [comment]
Thank you for running the tests! All warnings look sensible. Merging now

**Pull request merged**
