### PR TITLE
To pick up geometry v02_01

### PR DESCRIPTION
**Pull request by djpayne-thing**

### CODE REVIEW

**Comment by djpayne-thing** [comment]
CRT as built geometry, as of June 2024
Changes relative to previous gdml description:
Missing CRT_flat module replaced
2 Modules in north wall changed to square modules, placed as built
Modules at top of west side of north wall moved to their positions as built
Outer and inner layers of north wall switched so that horizontal modules are on the outside, as built
Screenshot 2024-06-13 114933
Screenshot 2024-06-13 115718

**Comment by djpayne-thing** [comment]
Also, CRT top layers have the spacing that they will have in the new design, but not the module content. Will need revision after it gets built

**Comment by henrylay97** [comment]
Great stuff, thanks @djpayne-thing!

@bear-is-asleep I will need to keep in the loop when this goes into a release so that I can make sure the channel mapping in that release matches this geometry.

I will test this next week with a list of other things I need to look at!

**Review by henrylay97 — CHANGES_REQUESTED** [review]
I have discovered some unexpected changes resulting from this geometry update.

Details are discussed offline in the #sbnd_crt slack channel, for those interested.

But for the sake of @bear-is-asleep - this PR should not be merged until further updates remove these changes.

**Comment by tomjunk** [comment]
I generally like to push the "Still in progress -- convert to draft" button in the top right just to make sure people don't approve and merge until further updates are made -- PR authors should do that.

**Review by henrylay97 — APPROVED** [review]
We've ironed out all the issues offline, I can now approve this PR.

However @bear-is-asleep this shouldn't be merged without a paired PR from me updating the channel mapping.

**Comment by marcodeltutto** [comment]
Thanks @henrylay97! Could you give a brief summary of the issues and how they were addressed?

**Comment by henrylay97** [comment]
So the issues all related to the positioning and orientation of the SiPMs / FEBs on each module.

As you know, the GDML doesn't actually specify the SiPMs or the FEBs, the modules are just scintillator and casing. However, the code (particularly in CRTGeoAlg) that interprets it has to make some assumptions in order to position the FEBs.

There were two problems discovered when I made some visualisations of this new version of the gdml:

1. Some modules in the north wall were inverted length ways - such that the FEB was placed in the centre of the wall not the outer edges.
2. Lots of modules had their FEB orientations (which end is ch0) inverted.

Number 2 was a mistake on my part, not realising the new channel mapping (which itself applies the required inversions) was being applied in the production of the visualisation.

Number 1 was genuine and results from the swapping of the two layers in the north wall. The logic in the CRTGeoAlg uses their relative positions to determine the ends of the FEBs. The best solution to this was to update the logic in the CRTGeoAlg which is done in the corresponding channel map PR that I referenced earlier today.

Final note is to say the visualisations I mentioned (after problems 1 & 2 were accounted for) can be found here https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=34844. This docDB will continue to be updated as each iteration of the CRT geometry is approved.

**Comment by bear-is-asleep** [comment]
Depends on [PR480](https://github.com/SBNSoftware/sbndcode/pull/480)

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00

**Comment by marcodeltutto** [comment]
Thanks very much, @henrylay97!

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbncode@v09_90_00

**Comment by marcodeltutto** [comment]
Unit tests fail at this line:
https://github.com/SBNSoftware/sbndcode/blob/3752f20d2ced2cf98081e46831a30a2283bb8e45/test/Geometry/CRTGeometry/SBNDCRTGeometryTest_module.cc#L89-L90
but I don't think this requirement is needed. I'll remove this line, which should let the unit tests succeed.

**Comment by marcodeltutto** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbncode@v09_90_00

**Comment by bear-is-asleep** [comment]
It looks like saving the GENIE event record is now throwing an error, which is a change from merging develop. I commented the line out to allow CI to run properly.

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbncode@v09_90_00

**Comment by bear-is-asleep** [comment]
Ok, the PR passed the CI by muting this change, so I will merge the PR since the CI passed safely.

**Pull request merged**
