### PR TITLE
CRT Offline - Reco

### PR DESCRIPTION
**Pull request by henrylay97**
## Description 
This is part of a set of PRs designed to integrate updates to the CRT reconstruction to run it on data. To split up the diffs into more easily reviewable chunks there are 5 PRs to a common base branch. Once these have all been merged I will make a single PR to develop containing the full set of updates. Note, only on the final PR should the CI be run!

This particular PR includes the core changes needed to run the CRT reconstruction on data, namely:
- Referencing the time of the first reconstruction product (strip hits) to the event trigger time.
- Accounting for scenarios in which the data lies near the boundary of a T0 increment and needs to be able to handle rollover effects.
- Allow use of either T0 or T1 (different clocks) to be used for clustering decisions.
- Retain both T0 & T1 throughout the reconstruction (coupled to the sbnobj updates).
- Creates fcl for running the CRT reconstruction standalone (a separate PR will be made once this is done to add it to the standard workflow).

Note, all these timing based changes should be transparent to MC reconstruction and are fcl configurable.

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Relevant PR links (optional)
The final PR will rely on one in `sbncode` and one in `sbnobj`

### Link(s) to docdb describing changes (optional)
CRT Data Reconstruction is detailed here: https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=36812

### CODE REVIEW

**Review by absolution1 — COMMENTED** [review]
Looks good to me @henrylay97 
I think I have one simple question before approving
 - Do we need to maintain a separate data workflow and an MC workflow?

**Comment by henrylay97** [comment]
Thanks @absolution1 

Short answer is yes. At least for now. There are a few fcl parameters (mainly in the 1st stage, strip hit making) that are introduced here to add these differences. They're not fundamental differences to how the algorithm operates but are mainly pre-processing steps that get the time variable from the data to look like the slightly simpler time created by the MC and used to make most algorithm decisions.

**Comment by absolution1** [comment]
Good to know, thanks @henrylay97 
We'll need to make sure that this is accounted for in the data reco fcls

**Review by absolution1 — APPROVED** [review]
Thanks @henrylay97

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by henrylay97** [comment]
Agreed! I will follow up these PRs with one to add the CRT data reconstruction to the workflow properly.
 I can imagine a way in which

**Pull request merged**
