### PR TITLE
Adding electronics response calibration + wire # bugfix

### PR DESCRIPTION
**Pull request by lynnt20**
## Description 
Adds feature to use the calibrated channel-by-channel parametrized electronics responses in WireCell signal processing for data. The parameters are stored in `sbnd-params-chresp-ideal-v1.json.bz2`, which can be found in the `WireCell` folder in `sbnd_data`. This version of the calibration assumes the **ideal electronics response only**, and only calibrates the gain and shaping time of each channel. We do not correct for undershoot/overshoot effects due to imperfect pole-zero cancellation.

This PR also implements a bugfix related to the new geometry; a previous configuration line for WireCell in the channel selector was overlooked, now the correct total number of channels is in place for both data/MC configuration jsonnets. 

Updated `sbnd_data` with the new file and updated changelogs can be found at `/exp/sbnd/app/users/lynnt/wirecell/sbnd_data/v01_25_00`. 
There's only the addition of a new file, so we can keep the same `sbnd_data` version, `v1_25_00`. 

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [N/A] Linked any relevant issues under `Developement`
- [N/A] Does this PR affect CAF data format? If so, please assign a CAF maintainer as additional reviewer.
- [x] Does this affect the standard workflow? 

### Relevant PR links (optional)
N/A

### Link(s) to docdb describing changes (optional)
Slides presenting the results of the calibration can be found in [docdb37765](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=37765).

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
To be clear @lynnt20 , we'll need to update `sbnd_data` before merging this correct?

**Comment by lynnt20** [comment]
yes please!! I will also be making one more commit today, sorry for the delay/trouble!

**Comment by bear-is-asleep** [comment]
No worries, am I free to update `sbnd_data` based on the path provided?

**Comment by lynnt20** [comment]
yes!

**Review by weihythu — APPROVED** [review]

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by lynnt20** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by lynnt20** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Pull request merged**
