### PR TITLE
CRT Decoder Updates

### PR DESCRIPTION
**Pull request by henrylay97**
This applies two updates to the CRT decoder. It is particularly important for the TITUS event display.

Firstly, the handling of modules with inverted channels is moved into the decoder (this was being handled in reconstruction, that data reconstruction is not yet in develop so doesn't require removing from anywhere in this PR).

Secondly, the cable delay is extracted from the timestamp field to store in the coinc field. This field (coinc) is not filled by the CRT hardware so is an empty field we can use to store this value. I will create a PR in sbnobj that adds a comment to the FEBData object (but this can go in without that).

### CODE REVIEW

**Review by eyandel — APPROVED** [review]

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
Hi Henry,

As you pointed out there are several warnings unrelated to this PR which I'll outline below (the ones with checks are good to go). They're mainly due to triggering on `sbncode v09_92_01_01` for the first time, which has GENIE and G4 physics list updates. Everything looks more less expected given the changes this PR brings in, including the new changes from `sbncode`, but the relevant people should verify, mainly the GENIE and CAF changes. 

[Link to all trigger tests](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/14655&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

#### sbncode updates
- [x] Updated physics list to `SBN_QGSP_BERT_NNC` (expected)
- [x] Updated geometry to v02_01 (expected)
- [ ] GENIE updates seen in CAFs, which should be validated by someone (@JosiePaton ?) who knows more about these changes - [link](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2024/07/23/stdout%23jVMEpxm.log)
- [ ] Differences in GENIE data product sizes - [link](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2024/07/23/stdout%2392JEMgl.log)
```
794: < GenieGen | generator |  | std::vector<simb::GTruth> | 2
795: ---
796: > GenieGen | generator |  | std::vector<simb::GTruth> | 1
```
#### sbndcode updates
- [ ] Some differences in the size of `crtsim` dataproducts which you should validate @henrylay97 
```
< DetSim | crtsim |  | art::Assns<sbnd::crt::FEBData,sim::AuxDetIDE,sbnd::crt::FEBTruthInfo> | 452
677: < DetSim | crtsim |  | std::vector<sim::AuxDetIDE> | 452
678: ---
679: > DetSim | crtsim |  | art::Assns<sbnd::crt::FEBData,sim::AuxDetIDE,sbnd::crt::FEBTruthInfo> | 439
680: > DetSim | crtsim |  | std::vector<sim::AuxDetIDE> | 439
681: 108c108
682: < DetSim | crtsim |  | std::vector<sbnd::crt::FEBData> | 327
683: ---
684: > DetSim | crtsim |  | std::vector<sbnd::crt::FEBData> | 323
```
- [x] Difference in `reco1` dataproduct size for `sedlite` which I checked and it's all good.
- [ ] Difference in `reco2` dataproduct size for various CRT objects which you should check @henrylay97 
```
2750: < Reco2 | crttracks |  | art::Assns<sbnd::crt::CRTSpacePoint,sbnd::crt::CRTTrack,void> | 108
2751: ---
2752: > Reco2 | crttracks |  | art::Assns<sbnd::crt::CRTSpacePoint,sbnd::crt::CRTTrack,void> | 107
2753: 311c311
2754: < Reco2 | crtspacepoints |  | art::Assns<sbnd::crt::CRTCluster,sbnd::crt::CRTSpacePoint,void> | 146
2755: ---
2756: > Reco2 | crtspacepoints |  | art::Assns<sbnd::crt::CRTCluster,sbnd::crt::CRTSpacePoint,void> | 148
2757: 315c315
2758: < Reco2 | crtclustering |  | std::vector<sbnd::crt::CRTCluster> | 154
2759: ---
2760: > Reco2 | crtclustering |  | std::vector<sbnd::crt::CRTCluster> | 159
2761: 373c373
2762: < Reco2 | crtspacepoints |  | std::vector<sbnd::crt::CRTSpacePoint> | 146
2763: ---
2764: > Reco2 | crtspacepoints |  | std::vector<sbnd::crt::CRTSpacePoint> | 148
```
- [ ] Difference in some header products in CAFs (@JosiePaton ?) - [link](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2024/07/23/stdout%23wxQ1IDy.log)
```
rec.hdr.sourceNameHash differs: 0 vs 653088054
```
- [x] Difference in some more geant4 products (expected due to physics list change)

**Comment by henrylay97** [comment]
Thanks Bear, this is an incredibly useful summary.

The two points of CRT difference you highlight would be a worry coming from this PR but they actually result from the recent GDML & channel map change so are not a concern. I am happy for this to proceed pending approval on other counts but we absolutely should update the references as soon as possible.

**Comment by henrylay97** [comment]
@bear-is-asleep is there are reason this is not merged yet? I can't see anything outstanding? Would be good to get this in as it is commissioning related

**Comment by henrylay97** [comment]
@tbwester I've added one tiny commit to this branch, we had one inversion out that I discovered in TITUS. I don't know what your method for picking up stuff into your "master branch" is but this is one to grab : )

**Comment by bear-is-asleep** [comment]
> @bear-is-asleep is there are reason this is not merged yet? I can't see anything outstanding? Would be good to get this in as it is commissioning related

Since the remaining data product checks are CAF/GENIE related (i.e. can't be fixed in sbndcode), we can merge.

**Pull request merged**
