### PR TITLE
Update unit tests to use WireCell workflow

### PR DESCRIPTION
**Pull request by fjnicolas**
Intended to match #409

### CODE REVIEW

**Comment by fjnicolas** [comment]
trigger build

**Comment by lynnt20** [comment]
Looks like the CI is still calling the old version of `standard_g4_sbnd.fcl` that includes `mcreco`. I think this may be expected?

**Comment by lynnt20** [comment]
Found another instance of `mcreco` in a g4 stage, in `g4_dirt_filter.fcl`. Unsure if this is the cause for the unit test failure, but should probably be changed in this PR 🥲  

https://github.com/SBNSoftware/sbndcode/blob/0f5b7c3ae8bd25509f3d624626203da94b97c3a5/sbndcode/JobConfigurations/standard/g4/g4_dirt_filter.fcl#L11

**Review by henrylay97 — APPROVED** [review]
Yeah looks good to me - once it's been shown Lynn's commit solves the failure.

@lynnt20 I notice some of the wirecell fcls have quite a lot of "other detsim things" commented out? Not necessarily one for this PR but might be worth removing to avoid confusion?

**Comment by fjnicolas** [comment]
> Looks like the CI is still calling the old version of `standard_g4_sbnd.fcl` that includes `mcreco`. I think this may be expected?

@lynnt20 what test do you mean? This PR only fixes the unit tests (they look fine to me in the previous build, other than the known issue with `c14` and CAF maker #407). The fix for the CI is not addressed here (coming PR from Rachel).

**Comment by lynnt20** [comment]
@fjnicolas oh I see, I misunderstood!! Everything looks good to me then!!

**Review by lynnt20 — APPROVED** [review]

**Pull request merged**
