### PR TITLE
CRT GDML Fixes

### PR DESCRIPTION
**Pull request by henrylay97**
## Description 
This PR fixes two outstanding issues relating to the CRT GDML
- The inversion of the east & west walls.
- The mis-assignment of strips to modules in the bottom CRT following GDML v02_01

It also makes a couple of minor aesthetic changes visible in the diffs from each commit.

There are other CRT GDML updates that are somewhat less pressing that will be followed in a future PR. See [docDB #37693](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=37693) for details of the changes made and those needed in future.

Note that, as module numbers do not change this PR does _not_ require a follow up channel map change.

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Relevant PR links (optional)
None

### Link(s) to docdb describing changes (optional)
See above

### CODE REVIEW

**Comment by marcodeltutto** [comment]
Thanks very much, @henrylay97! A PR (#496 by @lkashur) is already modifying the GDML creating v02_02. We should find a way to merge these two.

@lkashur, is the no. of wires change an easy modification? If so, could you maybe base your branch on this one and create v02_03 with the number of wires fix? Thank you!

**Comment by henrylay97** [comment]
@marcodeltutto ahhh good catch, sorry for not spotting this!

@lkashur I'm happy either way around. If your PR is ready to go I can wait for that to be merged and then apply my changes to your version?

**Comment by henrylay97** [comment]
Okay, thanks @lkashur! Sorry to create more work!

**Comment by bear-is-asleep** [comment]
Are we safe to close this? I'm under the impression that PR #499 covers this now.

**Comment by henrylay97** [comment]
We are indeed!

**Pull request closed without merging**
