### PR TITLE
Accommodate fiber swapped March 17 to enable half of the shorted FEM to be read out

### PR DESCRIPTION
**Pull request by tomjunk**
Thanks for merging PR431

https://github.com/SBNSoftware/sbndcode/pull/431

This PR accommodates a cabling change made on March 17 to enable half of the shorted FEMB to be read out.

This is the discussion Tingjun and I had today in Slack:

Tingjun Yang
  [11:49 AM]
Hi Tom, would it be possible to switch FEM 15 and 16 for NEVIS crate 8 in channel map? Thanks.

Tingjun Yang
  [12:46 PM]
This is for recovering the shorted FEMB

Tom Junk
  [6:32 PM]
Hi Tingjun -- okay, you can try it out at:  /exp/sbnd/data/users/trj/TPCChannelMap/March17_2024_swapFEMCrate8_FEM16_FEM17/SBNDTPCChannelMap_v1.txt
I did the following checks -- I verified that Run 11840 has no data with channels with FEMCrate == 8 and FEM == 16 or 17.  I swapped FEM 15 and 16 in the map file and put the new one above, and I re-decoded a file in Run 11840 and checked that nothing has changed. I ran my map checker on it and all 11264 channels are represented exactly once.

Tingjun Yang
  [6:45 PM]
Thanks Tom. It looks good! This is run 11944 with the shorted FEMB enabled. I had to ask Michelle to swap the cables connected to FEM 15 and 16 and exclude FEM 16 from DAQ. Your channel map put the channels back to the correct place.
evd twq-proj 11944 1800

### CODE REVIEW

**Review by yangtj207 — APPROVED** [review]

**Comment by yangtj207** [comment]
Thank you Tom. Hopefully this is the last needed change before we take physics data.

**Comment by fjnicolas** [comment]
@tomjunk @yangtj207, would you prefer to merge it now, or would you rather leave it open and merge it just before cutting the next release? Just in case you need to push any last-minute change

**Comment by tomjunk** [comment]
Thanks much!

**Comment by yangtj207** [comment]
Thank you!

**Pull request merged**
