### PR TITLE
Updated CRT Simulation

### PR DESCRIPTION
**Pull request by marcodeltutto**
This PR contains several updates to the CRT simulation, which are all discussed in detail in docdb [26031](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=26031). The docdb document also shows the validation performed.

Summary of changes:
- introduction of `FEBData` to store all 32 channels for each FEB
- `CRTData` is now constructed from `FEBData` objects with a new `CRTSlimmer` module
- CRT simulation triggering has been improved
- CRT waveform simulation has been implemented
- FEB dead time is now simulated
- CRT unit tests have been added

Depends on SBNSoftware/sbnobj#53.

### CODE REVIEW

**Review by eyandel — APPROVED** [review]

**Comment by fjnicolas** [comment]
trigger build [SBNSoftware/sbnobj#53](https://github.com/SBNSoftware/sbnobj/pull/53)

**Comment by fjnicolas** [comment]
trigger build SBNSoftware/sbnobj#53

**Comment by fjnicolas** [comment]
Hi @marcodeltutto! CI failed at build stage. From [LArSoft v09_50_00](https://github.com/LArSoft/larsoft/releases/tag/v09_50_00) an additional header is required to use the art::ServiceHandle. Could you add this? Thanks!

**Comment by marcodeltutto** [comment]
@fjnicolas, done! Thanks for providing the solution

**Comment by marcodeltutto** [comment]
trigger build SBNSoftware/sbnobj#53

**Comment by marcodeltutto** [comment]
trigger build https://github.com/SBNSoftware/sbnobj/pull/53

**Comment by marcodeltutto** [comment]
The CI test presents 4 warnings, all expected, so we should be good with merging this PR. We’ll need to re-make the reference files for the CI.

More details:

- `fcl_checks_sbndcode`: The crt fhicl `crtsimmodules_sbnd.fcl` has changed and the warnings are acknowledged.
- `nucosmics_detsim_quick_test_sbndcode` and `single_detsim_quick_test_sbndcode`: Module labels have changed, before we only had “crt”, now we have “crtsim” followed by “crt”.
- `nucosmics_reco2_quick_test_sbndcode` and `single_reco2_quick_test_sbndcode`: this test runs the reconstruction on an old detsim file. I had to change the reconstruction slightly to fix a problem with negative hit times being stored as int, which requires re-running the detsim stage, hence the warning.

**Pull request merged**
