### PR TITLE
Modify reco fcls so there's an option for not using the OpT0Finder

### PR DESCRIPTION
**Pull request by ikatza**
Just as the title says.

I'm open to suggestions about a neater way to achieve this.

### CODE REVIEW

**Comment by pgreen135** [comment]
The no flash matching fhicls should also disable the simplified flash matching -- otherwise the name is rather confusing!

**Review by marcodeltutto — APPROVED** [review]

**Review by pgreen135 — APPROVED** [review]
Thanks for updating the names @ikatza

**Comment by fjnicolas** [comment]
trigger build

**Comment by fjnicolas** [comment]
Hi @ikatza, unit tests failed for the `standard_reco1reco2_no_opt0finder_sbnd_lite.fcl` fhicl. Could you update the header to the `no_opt0finder` version? Thanks!

**Comment by ikatza** [comment]
Sorry for the oversight, I've pushed the rename.

**Comment by fjnicolas** [comment]
trigger build

**Comment by fjnicolas** [comment]
@ikatza can you have a look to the CIs? The `reco2` sequence is not well defined. I suggest defining it as `physics.reco2: [ @sequence::physics.reco2_no_opt0finder, opt0finder ]` outside the physics block.

**Comment by fjnicolas** [comment]
trigger build

**Pull request merged**
