### PR TITLE
EMB Recombination in Sim+Reco

### PR DESCRIPTION
**Pull request by gputnam**
Add in EMB recombination for simulation and reconstructed calorimetry. Add in g4_modbox fcl which conserves previous functionality.

### CODE REVIEW

**Comment by jzennamo** [comment]
OK, I have reviewed the changes to the code and they look good. I was able to compare the two following plots to verify that the change in simulation is working as expected and I ran through our full workflow to make sure nothing is broken.

Old Simulation:
image

New Simulation:
image

**Review by jzennamo — APPROVED** [review]

**Review by marcodeltutto — APPROVED** [review]
Looks good to me! Thanks @gputnam

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Pull request merged**
