### PR TITLE
Drop SimEnergyDeposits made by LArG4 in standard g4 workflow

### PR DESCRIPTION
**Pull request by marcodeltutto**
Fixes SBNSoftware/sbncode#185

### CODE REVIEW

**Comment by jzennamo** [comment]
Looking at a file from last production I see the following `sim::SimEnergyDeposits`:

```
sim::SimEnergyDeposits_ionandscint__G4.obj
sim::SimEnergyDeposits_ionandscint_priorSCE_G4.obj
sim::SimEnergyDeposits_ionandscintout__G4.obj
sim::SimEnergyDeposits_largeant_LArG4DetectorServicevolCryostat_G4.obj
sim::SimEnergyDeposits_largeant_LArG4DetectorServicevolFieldCage_G4.obj
sim::SimEnergyDeposits_largeant_LArG4DetectorServicevolPDSstructure_G4.obj
sim::SimEnergyDeposits_largeant_LArG4DetectorServicevolPMT_G4.obj
sim::SimEnergyDeposits_largeant_LArG4DetectorServicevolTPCActive_G4.obj
sim::SimEnergyDeposits_largeant_LArG4DetectorServicevolTPCPlaneVert_G4.obj
sim::SimEnergyDeposits_largeant_LArG4DetectorServicevolXArapuca_G4.obj
```

This PR would leave us with only:
```
sim::SimEnergyDeposits_ionandscint_priorSCE_G4.obj
```
I am happy with this but I'd also like to hear the thoughts of the SBN PDS and TPC Sim groups so I am adding them to the review for final sign off

**Review by jzennamo — APPROVED** [review]

**Comment by jzennamo** [comment]
@ggamezdiego could you pass word along to Alessandro as well?

**Comment by marcodeltutto** [comment]
Hi @jzennamo, thanks for summarizing! There is one more actually! This PR will leave us with
```
sim::SimEnergyDeposits_ionandscint_priorSCE_G4.obj    [energy deposit in AV]
sim::SimEnergyDeposits_ionandscintout__G4.obj         [energy deposit outside AV]
```

These are a copy of the largeant ones, but with the addition of electrons and photons.

The outside-AV one doesn't have the `priorSCE` label, but I understand we don't have SCE corrections outside the AV, so this is effectively a priorSCE collection. Please correct me if I'm wrong!

**Comment by jzennamo** [comment]
right! Thanks for catching my ommission!

**Comment by pgreen135** [comment]
trigger build

**Review by pgreen135 — APPROVED** [review]
CIs are as expected. I will wait on approval from the SBN PDS and TPC sim groups before merging.

**Review by ggamezdiego — APPROVED** [review]

**Comment by ggamezdiego** [comment]
> @ggamezdiego could you pass word along to Alessandro as well?

Done!

**Comment by jzennamo** [comment]
@mrmooney approved offline along with @gputnam, this is ready to be merged! 

Thanks @marcodeltutto!

**Pull request merged**
