### PR TITLE
Run mcreco with Dropped Particles

### PR DESCRIPTION
**Pull request by bear-is-asleep**
MCReco needs inputs from both MCParticle lists to track down ancestory of EM shower daughters.

I also tacked on some small changes to the reco stage that makes a separate analyzer module for mpvmpr.

Also some changes to mpvmpr generator.

All of these changes are isolated to the ml reco workflow and should not effect the standard reco workflows, especially since Pandora no longer uses mcreco.

This PR is dependent on [larsim PR133](https://github.com/LArSoft/larsim/pull/133) being merged into sbncode.

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
Sorry @lynnt20  and @fjnicolas this is a lot for a single PR, but it all is isolated to ML reco so it should still be easy to review.

**Comment by bear-is-asleep** [comment]
This

**Comment by bear-is-asleep** [comment]
> hi @bear-is-asleep is this needed por production or can get in later? I was planning to cut production release based on current develop and `larsoft/sbncode v09_88_00`

It's low priority to get in, so if it holds up production please feel free merge it afterwards!

**Comment by fjnicolas** [comment]
trigger build

**Review by fjnicolas — APPROVED** [review]

**Pull request merged**
