### PR TITLE
CRT Plane Index and Commissioning Samples

### PR DESCRIPTION
**Pull request by marcodeltutto**
This PR:
- From Michelle: adds a `GetPlaneIndex` function in `CRTCommonUtils` to retrieve the CRT plane index. This is also saved in the CRT Hit dataproduct.
- Fixes the CRT plane names: Front, Back, Left, Right -> South, North, West, East
- Makes sure that the commissioning detsim fhicl saves the full optical waveforms 

This PR is also needed to generate the commissioning samples for the current 2021C production.

### CODE REVIEW

**Comment by pgreen135** [comment]
@marcodeltutto if I'm understanding correctly, is a patch release required for SBN2021C? if so, this branch is based off of develop so cannot (easily) be merged into the release/SBN2021C branch --- could you instead make a branch based off the current SBN2021C release (v09_37_01_03) with these changes

**Comment by marcodeltutto** [comment]
Yes, sure. Of course we also want these fixes in develop for the future. Do you merge the release branch into develop later on, or shall open 2 PRs?

**Comment by pgreen135** [comment]
A single PR is fine, as long as the branch is compatible with release/SBN2021C it is easy enough to also merge into develop (which I'll do that when I next do a weekly release). Thanks!

**Comment by marcodeltutto** [comment]
Replace by PR #250.

**Pull request closed without merging**
