### PR TITLE
CRUMBS develop

### PR DESCRIPTION
**Pull request by henrylay97**
As requested @pgreen135

Having a couple of issues with the CAF CI tests which I'm hoping to dig into today whilst travelling

### CODE REVIEW

**Review by pgreen135 — APPROVED** [review]
Thanks @henrylay97, let me know once the CI issues are resolved / this is ready to be merged

**Comment by henrylay97** [comment]
Just to update on here. Got waylaid by launching the production and came back to this yesterday. Ran some CI tests which can be seen here for [e20:prof](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/9288&platform=Linux%203.10.0-1160.59.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof) and [c7:prof](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/9289&platform=Linux%203.10.0-1160.59.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

Some of the changes are understood but there are some caf changes in e20 and the caf failures in c7 that need more investigation. I will pursue this offline and update here when I'm happy.

**Comment by henrylay97** [comment]
This is good to go now! Issues with CI indicated a separate issue which is fixed by the above sbncode PR. Remaining differences are expected.

**Comment by pgreen135** [comment]
Thanks @henrylay97, we will include this in the release this week.

**Comment by pgreen135** [comment]
trigger build SBNSoftware/sbncode#262

**Pull request merged**
