### PR TITLE
Feature/lynnt_pmt_trig updates to PMT software trigger module 

### PR DESCRIPTION
**Pull request by lynnt-uchicago**
updates to the whole PMT trigger simulation chain (linked with pull request in sbnobj: https://github.com/SBNSoftware/sbnobj/pull/48)

### CODE REVIEW

**Review by mstancar — APPROVED** [review]

**Comment by pgreen135** [comment]
trigger build

**Comment by pgreen135** [comment]
trigger build SBNSoftware/sbnobj#48

**Comment by pgreen135** [comment]
@lynnt-uchicago see build failure above,

```
2024: /scratch/workspace/sbnd_ci/label_exp/SLF7/label_exp2/swarm/SBND/srcs/sbndcode/sbndcode/Trigger/pmtSoftwareTriggerProducer_module.cc:234:19: error: use of undeclared identifier 'ADCThreshold'
2025:         if (adc < ADCThreshold){ nAboveThreshold++; break; } 
2026:
                   ^
```

**Comment by lynnt-uchicago** [comment]
@pgreen135 fixed the typo! apologies for the silly bug

**Comment by pgreen135** [comment]
trigger build

**Comment by pgreen135** [comment]
trigger build SBNSoftware/sbnobj#48

**Pull request merged**
