### PR TITLE
Reset LArFFT service in CalWireSBND module

### PR DESCRIPTION
**Pull request by fjnicolas**
Intended to fix issue #300

### CODE REVIEW

**Comment by absolution1** [comment]
Hi Fran.  The changes by eye look good to me.
It would be a good idea to trigger the validation system to check that the output doesn't actually change (the output shouldn't change here, right?)

**Comment by fjnicolas** [comment]
Hi Dom, thanks for your answer. The PR shouldn't change the output. The MC reco validation suite for the test sample can be found in this [link](https://dbweb9.fnal.gov:8443/TestCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/10255&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_validation&buildtype=slf7%20e20:prof). Refs are not up to date, hence the bunch of unexpected errors/warnings 

For comparison I triggered the CI suite for the `v09_58_02_01` tag (link [here](https://dbweb9.fnal.gov:8443/TestCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/10259&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_validation&buildtype=slf7%20e20:prof)) and the same warnings/errors are obtained. The chi2 values are identical for the CI trigger with and wo the changes, so the PR doesn't seem to modify the output as expected.

Not the best way to test it, but from conversation with the CI team the new refs may take some delays, so I hope this can help the PR going forward.

**Review by absolution1 — APPROVED** [review]
Thanks for making the requested changes.  The code looks great.
Approved!!!

**Comment by fjnicolas** [comment]
trigger build

**Pull request merged**
