### PR TITLE
Add photon propagation times to hybrid model and re-enable by default

### PR DESCRIPTION
**Pull request by pgreen135**
Adds photon propagation times calculation for external regions in hybrid model and re-enables hybrid model by default. Requires https://github.com/LArSoft/larsim/pull/84. Resolves https://github.com/SBNSoftware/sbndcode/issues/219.

### CODE REVIEW

**Comment by pgreen135** [comment]
@ggamezdiego https://github.com/LArSoft/larsim/pull/84 has now been merged and included in v09_40_00. Is this ready to be re-activated, or are there still issues with the library?

**Comment by ggamezdiego** [comment]
The issue with the library is still there. But this PR is "independent" on this issue. I mean, the PR can go in and the library could be updated later. If you @pgreen135 agree, I will proceed with the approval

**Comment by pgreen135** [comment]
okay, I can include this in this weeks release

**Comment by pgreen135** [comment]
trigger build

**Review by ggamezdiego — APPROVED** [review]

**Comment by pgreen135** [comment]
CI test changes are as expected

**Pull request merged**
