### PR TITLE
Update ophitfinder parameters to run on raw waveforms

### PR DESCRIPTION
**Pull request by asanchezcastillo**
## Description 
Change OpHitFinder parameters to run on raw PMT signals. 

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Relevant PR links (optional)
Does this PR require merging another PR in a different repository (such as sbnanobj/sbnobj etc.)?

### Link(s) to docdb describing changes (optional)
[docdb 37325](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=37325)

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
Do you have any validation plots/work to accommodate this?

**Comment by asanchezcastillo** [comment]
> Can you also update the values here so everything that runs on raw waveforms is updated? https://github.com/SBNSoftware/sbndcode/tree/develop/sbndcode/Trigger/PMT. We should work towards making a fcl that contains these values in a future PR.

Done

**Comment by bear-is-asleep** [comment]
Ok all looks well, thanks for updating! Please include the docDB link in the initial PR message in the future, I've editted it to include your doc.

**Review by bear-is-asleep — APPROVED** [review]

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 SBNSoftware/sbncode@v09_91_02_02

**Comment by RachelCoackley** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 SBNSoftware/sbncode@56dc342f SBNSoftware/sbnobj@a4b93770 SBNSoftware/sbndcode@e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
Approved for merge

**Pull request merged**
