### PR TITLE
Add facility to deaden readout channels (and kill some of the channels that are unphysical)

### PR DESCRIPTION
**Pull request by absolution1**
As the title says, this PR adds in the ability to deaden channels in the sim/reco.
I've opted to kill the channels when the detector response is being run so that the sim channels remain intact.

I've also deadened some unphysical channels.
See this docdb entry for more information: https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=21576

I would like to trigger the full validation system before merging, just to make sure this doesn't do anything nasty to the shower reconstruction

Requesting review from TPC sim+calib/commissioning/infrastructure.

Thank you!

### CODE REVIEW

**Comment by mstancar** [comment]
I'm happy with the presentations at the PAT meeting that show this code change is relevant and functional

**Comment by henrylay97** [comment]
The standard CI [tests](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/6342&platform=Linux%203.10.0-1160.21.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e19:prof) and the reconstruction [validation](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/6342&platform=Linux%203.10.0-1160.21.1.el7.x86_64&phase=ci_validation&buildtype=slf7%20e19:prof) have been run on this PR.

**Comment by jzennamo** [comment]
sorry for my delayed review but this looks great and tidy. One silly question is how simchannels are handled now. Will we still create simchannels for these bad channels and then just not promote them to RawDigits during the detsim stage?

**Comment by absolution1** [comment]
Exactly that.  The simchannel will still exist and receive true charge.  The signal simulation will simply ignore the channels and not produce an output for them.

**Comment by jzennamo** [comment]
Perfect, that sounds like exactly what we'd like. Approved on my end!

**Comment by pgreen135** [comment]
@absolution1 is this ready to be merged into this weeks release? or @mrmooney did you wish to also have a look at this first?

**Comment by absolution1** [comment]
I wasn't planning on adding anything else to this PR unless reviewers required agreed changes.  So, I'm happy for it to go in.

**Pull request merged**
