### PR TITLE
Update to flux config J 

### PR DESCRIPTION
**Pull request by VCLanNguyen**
1. Update default flux from config H to config J

Flux config J contains a new variable vtxt that stores kaon and neutrino time of flight from production to flux window.
See docdb# 30136 for validation plots (https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=30136)

### CODE REVIEW

**Comment by VCLanNguyen** [comment]
trigger build

**Comment by marcodeltutto** [comment]
Thanks so much, @VCLanNguyen for working on this - it's really great to have the neutrino time in. 

It looks like the CI validation has some warnings also in previous builds, so it's a bit hard to tell. This PR will include a ~330 ns offset and I would be surprised if this causes problems, but we should really make sure the reconstruction is not affected. Do you know if the CI reconstruction stage start from reference detsim files (which don't have the neutrino time in), or does it start from new gen files, which will have the neutrino time in?

**Comment by fjnicolas** [comment]
Hi @marcodeltutto @VCLanNguyen! Most of the warnings are related to the changes in the hit finder algorithm introduced in SBNSoftware/sbndcode#318, but I agree we should make sure this PR is not affecting our reconstruction. We had a new release yesterday and @RachelCoackley is now working on getting new ref files. We can trigger the CI again after that to check nothing is changed

**Comment by fjnicolas** [comment]
trigger build

**Comment by marcodeltutto** [comment]
Thanks, @fjnicolas! Just one thing I wanted to make sure of: does the CI reconstruction stage start from reference detsim files (which don't have the neutrino time in, and so the test is not telling us much), or does it start from new gen files, which will have the neutrino time in? Thanks!

**Comment by henrylay97** [comment]
@marcodeltutto the former is correct. The reco test is run on reference detsim files without the neutrino time. @RachelCoackley can run the sequential tests for you. They are used in precisely this kind of scenario where we care about the knock-on impact of upstream changes. Rachel, feel free to slack me for the gory details :)

**Comment by RachelCoackley** [comment]
The sequential tests have been done and can be seen here: https://buildmaster.fnal.gov/buildmaster/job/sbnd_ci/11434. I can't access the site myself right now as it wont load (I could only have a quick check and there are some warnings) but wanted to post it before I log off for the night. I will have a proper look tomorrow!

**Comment by henrylay97** [comment]
https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/11434&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof here's the direct link to the results.

**Comment by VCLanNguyen** [comment]
The error messages are mostly to do with memory usage and product size. Is this consistent with the warning from the hit finding algorithm? Can @fjnicolas @henrylay97 @RachelCoackley have a second look to confirm this?

**Comment by RachelCoackley** [comment]
Okay, so I’ve had a look through and a lot of the warnings are about the memory usages, etc (so I assume they’re fine). There were 2 tests that had different warnings in the sequential tests to the quick tests: fcl_checks_sbndcode and nucosmics_g4.

The fcl_checks_sbndcode sequential test had some differences, quite a few were “AddGenieVtxTime:true” being added. The others were changes in a root file name and a change in the FluxSearchPath. (The output file for fcl_checks_sbndcode sequential tests: https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2023/03/08/stdout%23U9zrnSg.log)

The nucosmics_g4 had a few differences in the sizes of data products. For run: 1 subRun: 0 event: 1, the difference in sizes were:
- sim::AuxDetSimChannel: 391 in seq tests (line 1723 in seq output file), 381 in quick tests (line 1528 of quick output file)
- sim::MCShower: 107 in seq tests (line 1733), 105 in quick tests (line 1538)
- sim::SimEnergyDeposit: 218906 in seq tests (line 1734), 214018 in quick tests (line 1539)
- simb::MCParticle: 3860 in seq tests (line 1735), 4218 in quick tests (line 1540)
- sim::SimChannel: 8808 in seq tests (line 1740), 8418 in quick tests (line 1545)
- sim::MCTrack: 383 in seq tests (line 1742), 388 in quick tests (line 1547)

I had a look at the other events and these products were again different between the seq and quick tests. All others were unchanged. All of the differences for all of the events run are at the very bottom of the nucosmics_g4 sequential test output file, if you want to see all of them!

The sequential test output file for nucosmics_g4 is here: https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2023/03/08/stdout%23JfaQBau.log

The quick test output file for nucosmics_g4 is here: https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2023/03/03/stdout%23WlGZAiB.log

**Comment by henrylay97** [comment]
@VCLanNguyen @RachelCoackley Resource usage warnings are basically irrelevant for the sequential tests. The reference files have been updated recently so none of this has anything to do with the hit finding stuff.

There are product differences in all `nucosmics` tests from g4 onwards (as I'd expect to see). This is consistent with the fact that any change to genie/flux will probably result in a completely different neutrino interaction and thus everything downstream will be different (not just time). This is indicated again in the `nucosmics_caf` test where (in and amongst 1000s of lines of differences you can see that the details of the neutrino interaction in truth are different. It's impossible to distinguish what comes from changing to flux J and what comes from the activation of the time component.

I should note that there is a reason we don't see any changes at the `nucosmics_gen` despite this being the stage directly affected by the change. The checks just look for product differences, this highlights some things more than others. In the case of genie generation, this is essentially looking for whether the number of `MCTruth` objects has changed. Given this is almost always 1 (occasionally 2) this rarely shows up a difference, even if the details of the neutrino interaction are completely different. Clearly this has much more power on detsim or reco stage objects that are produced in much larger numbers. The `nucosmics_caf` test does show that the details of the neutrino interaction have indeed changed.

My thoughts are:
- Lan have you done any validation through reconstruction or just at the truth level?
- Is it possible / worthwhile to separate out this PR into 2?
       - The first changes the flux file to J, your plots support the fact that this flux is consistent with H
       - Another which activates the _use_ of the time variable. This should be a much more limited change and should help us validate its effect?
       
This may well be overkill, it depends how confident we are on this change :)

**Comment by VCLanNguyen** [comment]
@henrylay97 @RachelCoackley @fjnicolas @rodralva 
I haven't done any reconstruction validation test apart from comparing the flux at truth level. 
Do you guys have any suggestions for a reco validation tests that would be able to pick up changes like this? TPC reco? PDS reco? 
We can do some the validation offline before committing this PR.

**Comment by VCLanNguyen** [comment]
Update the PR to only "update from config H to config J". (Removed the enable genie time)

**Comment by VCLanNguyen** [comment]
trigger build

**Comment by RachelCoackley** [comment]
Here's the link to the sequential tests done for this PR: https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/11442&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof

**Comment by VCLanNguyen** [comment]
@RachelCoackley @henrylay97 I checked the logs for `nucosmics_caf` and see the products difference and changes in some downstream vectors. Does this indicate that there's indeed changes in the new flux file?

**Comment by henrylay97** [comment]
@VCLanNguyen 

So as anticipated, the changes are still _very_ large in number (see the diff in the [nucosmics_caf](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2023/03/09/stdout%23j3dHOfB.log) for the sequential tests).

This makes perfect sense. The flux files are the same at a high stats scale but of course we are sampling a different neutrino interaction than before. See for example these lines:

> 20912:   rec.mc.nu[0].prod_vtx.x differs: 1.7282639741897583 vs -2.5668458938598633
> 20913:   rec.mc.nu[0].prod_vtx.y differs: -0.7034727931022644 vs -10.588994979858398
> 20914:   rec.mc.nu[0].prod_vtx.z differs: 1405.032958984375 vs 1407.4989013671875
> 20915:   rec.mc.nu[0].q0_lab differs: 0.7450191974639893 vs 0.15539957582950592
> 20916:   rec.mc.nu[0].resnum differs: 0 vs -1

The neutrino interaction point & kinematics are different. In the sequential tests, this difference then propagates through (and gets amplified at every stage). We start with a completely different physics event so we will expect that almost every downstream product at simulation or reconstruction will have changed.

We don't see _any_ product differences in any stage for the non-sequential (standard) tests. Again this is consistent because in this scenario, the change of neutrino does _not_ propagate downstream.

I'm happy for this to be merged (assuming @RachelCoackley @marcodeltutto @jicrespo etc also are), then we can test the activation of the time component in a separate PR.

**Review by marcodeltutto — APPROVED** [review]
Sounds good to me. Thank you!

**Pull request merged**
