### PR TITLE
New XAs PDEs to VUV and visible light

### PR DESCRIPTION
**Pull request by rodralva**
New data-driven proposed PDEs based on CIEMAT measures and analysis, summary can be found here:
[https://docs.google.com/presentation/d/17mvsNqaZfgkvTXj8s4t61ZNk1JXJdCT6hNuyQc7cJvg/edit?usp=sharing](
https://docs.google.com/presentation/d/17mvsNqaZfgkvTXj8s4t61ZNk1JXJdCT6hNuyQc7cJvg/edit?usp=sharing)

### CODE REVIEW

**Comment by fjnicolas** [comment]
@rodralva can you also add a comment in the fhicl with the docdb entry for future reference?

**Comment by fjnicolas** [comment]
PR waiting for approval in an upcoming SBND reco meeting.

**Review by jicrespo — APPROVED** [review]

**Comment by fjnicolas** [comment]
trigger build

**Comment by fjnicolas** [comment]
trigger build

**Pull request merged**
