### PR TITLE
Signal processing configuration

### PR DESCRIPTION
**Pull request by ebelchio12**
Add fcls for wire-cell 2D signal processing

### CODE REVIEW

**Comment by fjnicolas** [comment]
@weihythu @yangtj207 @mrmooney could you take a look at this PR? Thanks!

**Review by weihythu — CHANGES_REQUESTED** [review]
Please add a workflow (jsonnet) that bypasses noise filtering. In the near future production, we may want to exclude noise filtering since it is just a placeholder now with protoDUNE coherent noise removal setup.

**Review by weihythu — APPROVED** [review]

**Review by weihythu — APPROVED** [review]

**Comment by fjnicolas** [comment]
trigger build

**Comment by RachelCoackley** [comment]
Warnings for the ci tests are consistent with the warnings from the overnight ci tests. Also tested this PR with updated reference files: https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/12193&platform=Linux%203.10.0-1160.88.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof

**Pull request merged**
