### PR TITLE
Cosmic InTime Workflow with Refactored LArG4

### LINKED ISSUE #147: Check Gen and G4 InTime FHiCLs with Refactored LArG4
As mentioned in PR #134, the `prodcorsika_proton_intime_filter.fcl ` and `g4_simphotontime_filter.fcl`, will have to be reviewed to make sure the in-time and out-time paths are both running correctly. Same is true for all intime fcls.

### PR DESCRIPTION
**Pull request by marcodeltutto**
This PR adds a workflow for making intime samples with the new larg4 simulation. Fixes #147. 

Depends on: 
- LArSoft/larg4#30
- LArSoft/larsim#76

With the new larg4 we have a proliferation of modules that we need to run to get all the TPC, PDS, and CRT simulated products. It's much harder to bookkeep all of this when dealing with our intime workflow, where we first simulate in-time cosmics, then out-time ones, and then we merge them together. I made this flowchart to try and not forget anything, which I hope will be useful for the future as well.

InTime Workflow drawio

The fcls to run are:
- `prodcorsika_proton_intime_filter.fcl`, or `prodcorsika_proton_intime_filter_sce.fcl`
- `g4_simphotontime_filter.fcl`
- `standard_detsim_sbnd.fcl` and the usuals...

### CODE REVIEW

**Comment by jzennamo** [comment]
This looks excellent! One quick question, does the CI test the in-time cosmic workflow laid out here? Have we tested that it does in fact run?

**Comment by pgreen135** [comment]
@jzennamo no, the CI does not run this -- you/Marco should definitely test this is working before we merge it!

**Comment by jzennamo** [comment]
OK! I merged this branch into v09_35_00 and I'll see if I can complete the same workflows Marco laid out above

**Comment by jzennamo** [comment]
OK, my findings:
For the gen stage I ran `prodcorsika_proton_intime_filter_sce.fcl` and got:
`Events total = 500 passed = 4 failed = 496` --> ~1% pass rate, this matches what we had for MCP2020

Then I ran `g4_sce_simphotontime_filter.fcl`, `detsim_sce.fcl`, `reco1_sce.fcl`, and `reco2_sce.root`

In 4 events there is on average ~11 tracks which seems reasonable and they are reasonably distributed across the TPC. 

**one comment**, the gen stage creates a "hist file" with `_hists` appended to the end, while all other stages add `hists_` to the front, could this be changed before it is merged? 

Save this one very minor comment I am happy for this to move forward!

**Comment by marcodeltutto** [comment]
Thanks @jzennamo! I fixed the hist file name with commit 9f057a4.

**Review by jzennamo — APPROVED** [review]

**Comment by jzennamo** [comment]
Approved! Thanks again!

**Pull request merged**
