### PR TITLE
Feature/brindenc

### PR DESCRIPTION
**Pull request by bear-is-asleep**
Editted hitdumper fcl files so muon tracks can be read into them.

### CODE REVIEW

**Review by marcodeltutto — COMMENTED** [review]
Hi @bear-is-asleep! Looks good to me, thanks! Just one question: it looks like you are also adding the MuonTrackFilter, this means that only filtered events will be saved in the output tree, right? Is this ok also for all the other HitDumper's users?

**Comment by bear-is-asleep** [comment]
> Hi @bear-is-asleep! Looks good to me, thanks! Just one question: it looks like you are also adding the MuonTrackFilter, this means that only filtered events will be saved in the output tree, right? Is this ok also for all the other HitDumper's users?

no this would not be ideal for all users, so we can default to not including the filter line in the hitdumper stream path

**Comment by bear-is-asleep** [comment]
> > Hi @bear-is-asleep! Looks good to me, thanks! Just one question: it looks like you are also adding the MuonTrackFilter, this means that only filtered events will be saved in the output tree, right? Is this ok also for all the other HitDumper's users?
> 
> no this would not be ideal for all users, so we can default to not including the filter line in the hitdumper stream path

i've commented out the filter line

**Review by marcodeltutto — APPROVED** [review]

**Comment by RachelCoackley** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_03 SBNSoftware/sbncode@v09_75_03

**Comment by RachelCoackley** [comment]
Hi @bear-is-asleep, the unit tests failed during the CI. I think this is because of line 96 in run_hitdumper.fcl due to the comma at the end of MuonTrackProducer when it is the last variable in the list (unless MuonTrackFilter isn't supposed to be commented out?) Please would you be able to update the file to fix this? Thanks!

**Comment by lynnt-uchicago** [comment]
hey all, sorry for not being able to look at this earlier; I'm looking through the files now!

**Comment by bear-is-asleep** [comment]
I've updated such that line 96 is commented out. It seems the muon producer doesn't work without the filter, so we probably don't want to run the muon producer/filter by default. @lynnt-uchicago please let me know if this seems reasonable.

**Comment by lynnt-uchicago** [comment]
Yup that's reasonable! you should change the default on the hitdumper fcl to reflect that the muon track module will not be run.

**Comment by RachelCoackley** [comment]
Let me know when this is ready to go through the CI tests again! :)

**Comment by bear-is-asleep** [comment]
> Let me know when this is ready to go through the CI tests again! :)

@lynnt-uchicago I've changed the defaults in the hitdumper fcl. I believe that we're ready for the CI test @RachelCoackley

**Comment by RachelCoackley** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_03 SBNSoftware/sbncode@v09_75_03

**Comment by RachelCoackley** [comment]
Hi @bear-is-asleep , sadly it failed the CI on the unit test stage again, you can see the log [here](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2023/07/26/testFHiCLfiles_sbnd.sh%23t8tkse9.log). It’s in the same section as last time (I think on line 95) in run_hitdumper.fcl. I think this might be due to the comma at the end of `ophitarapuca,` with it being the last in the reco2 list. I think it can be fixed by changing it to `ophitarapuca` instead?

**Comment by RachelCoackley** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_03 SBNSoftware/sbncode@v09_75_03

**Pull request merged**
