### PR TITLE
CRT Decoder & Channel Map

### PR DESCRIPTION
**Pull request by henrylay97**
I've extracted the CRT decoder and channel map from the offline reconstruction branch we've been working on at FNAL. This should be enough to start adding the CRT decoder to the automatic decoder processes.

Note that this implementation of the channel map only contains the North, East and Flat modules. The West wall is currently in the data stream, channel map to come. There are also 3 modules (2 on the north and 1 on the flat) which have no corresponding module in the current geometry version. The decoder deals with this gracefully, putting a message in the log and printing a summary message to `cout` at the end of the job with a summary of which modules it didn't find.

### CODE REVIEW

**Comment by henrylay97** [comment]
@tbwester note the update today to include the West Wall. Thanks to Nikki Pallat!

**Review by tomjunk — APPROVED** [review]
Looks good!  Sorry to be slow!

**Comment by RachelCoackley** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00 SBNSoftware/sbncode@v09_90_00 SBNSoftware/sbndcode@v09_90_00

**Comment by henrylay97** [comment]
Sorry to update it just after it's been reviewed. The updates are very minor and correspond to: 
- an updated channel map text file (corrects a couple small errors we found looking at the data & provides the addition of the South wall)
- hides a log statement behind a debug flag to avoid bloating

@tbwester updates as promised, sorry for the delay!

**Comment by bear-is-asleep** [comment]
Is this PR now contingent on geometry changes from [PR478](https://github.com/SBNSoftware/sbndcode/pull/478)? I'm just wondering so I know if these need to be merged at the same time for example.

**Comment by henrylay97** [comment]
Nope this could go in now. But as I mentioned in #478 it will require a further update which I could either add to this if still open, or make in a separate PR next week.

**Comment by bear-is-asleep** [comment]
> Nope this could go in now. But as I mentioned in #478 it will require a further update which I could either add to this if still open, or make in a separate PR next week.

Hi Henry, I'm happy to do either, although I have a slight preference towards just adding the change to this code. Just let me know which one you'd like and your wish will be granted.

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00

**Comment by tomjunk** [comment]
Sorry to be slow!  Just seeing this.  Looks like minor changes and of course any fixes to the mapping should go in.

One comment about verisoned map files  -- if they are needed to read old and new data, then yes, absolutely keep each version with a version number.  If a particular file contains a mistake and corresponds to no data at all, you can overwrite it with the corrected map -- no need to keep the incorrect one around in the release.  But if the detector itself evolves, or the data format or even the larsoft geometry, then absolutely, keep the versions.

**Review by tomjunk — APPROVED** [review]
Approved

**Pull request merged**
