### PR TITLE
transfer code from old feature branch

### PR DESCRIPTION
**Pull request by mstancar**

### CODE REVIEW

**Comment by pgreen135** [comment]
This PR contains a tidied up version of the updates in https://github.com/SBNSoftware/sbndcode/pull/171.

Description copied from there: 

Updates to the CRT hit - TPC track matching algorithm that were described in docdb 22851

**Comment by wesketchum** [comment]
I think this requires #143 completed in order to appropriately test prior to merge. In the meantime, we should make sure it doesn't follow too far behind develop.

@pgreen135 can we update this against develop this week, to be sure we don't get too far behind. Also, a test build may then be warranted?

**Comment by pgreen135** [comment]
@wesketchum yes can do

**Comment by wesketchum** [comment]
I think we may be getting closer to having the CRT issues fixed.

@pgreen135 can we update this against develop? If not successful, we'll need to spend some time to resolve any issues...

**Comment by pgreen135** [comment]
@wesketchum done, no conflicts. Let me know when this is ready to be merged

**Comment by pgreen135** [comment]
and builds successfully too!

**Comment by wesketchum** [comment]
I'm assigning this to @mstancar and @ilepetic for the moment, just to encourage that this be tested once the other CRT fixes are in place for SBND.

**Comment by wesketchum** [comment]
@pgreen135 I believe that is the case! When you can, please update this to a real PR and let's get it in!

**Comment by pgreen135** [comment]
trigger build

**Comment by pgreen135** [comment]
This is failing the unit tests with the following error:

```
43: %MSG-s ArtException:  PostEndJob 22-Nov-2021 11:37:39 CST ModuleEndJob
44: ---- EventProcessorFailure BEGIN
45:   EventProcessor: an exception occurred during current event processing
46:   ---- DictionaryNotFound BEGIN
47:     No dictionary found for the following classes:
48:     
49:          art::Assns<anab::T0,sbn::crt::CRTHit,void>
50:          art::Assns<sbn::crt::CRTHit,anab::T0,void>
51:          art::Wrapper<art::Assns<anab::T0,sbn::crt::CRTHit,void> >
52:          art::Wrapper<art::Assns<sbn::crt::CRTHit,anab::T0,void> >
53:     
54:     Most likely they were never generated, but it may be that they were generated in the wrong package.
55:     
56:     Please add (or move) the specification
57:     
58:          <class name="MyClassName"/>
59:     
60:     to the appropriate classes_def.xml file.
61:     
62:     Also, if this class has any transient members,
63:     you need to specify them in classes_def.xml.
64:   ---- DictionaryNotFound END
65: ---- EventProcessorFailure END
66: %MSG
```

**Comment by wesketchum** [comment]
On it ...

**Comment by etyley** [comment]
There is an associated sbnobj branch: https://github.com/SBNSoftware/sbnobj/tree/feature/mstancar_CRTtimetag/sbnobj

**Comment by pgreen135** [comment]
thanks @etyley, can either you or @mstancar make a PR for that branch too then

**Comment by pgreen135** [comment]
trigger build SBNSoftware/sbnobj#34

**Comment by pgreen135** [comment]
trigger build SBNSoftware/sbnobj#34

**Comment by etyley** [comment]
The warnings in product sizes are expected due to the harsher cuts being placed on the CRT-TPC matching and additional association between the T0 and the CRT hit

**Comment by pgreen135** [comment]
great, thanks @etyley 

from my side this looks ready to go -- does this want to be merged into the SBN2021C branch (to be included in the next patch) or just to develop? @wesketchum

**Comment by jzennamo** [comment]
I would vote it gets merged into SBN2021C branch (and develop), thanks everyone!

**Comment by pgreen135** [comment]
okay, I've updated these PRs (sbnobj too) to point towards the SBN2021C branches

**Review by jzennamo — APPROVED** [review]

**Pull request merged**
