### PR TITLE
Reco2 pandoraCalo and pandoraPID with initial calibration constants from data 

### PR DESCRIPTION
**Pull request by sungbinoh**
## Description 
Apply first calibration constants measured using data, Run 14860, for reco2_data.fcl.

Since pandoraCalo and pandoraPID are defined in the reco_sbnd.fcl as
`pandoraCalo:         @local::sbnd_gnewcalomc`
`pandoraPid:          @local::sbnd_chi2pid`,
pandoraCaloData and pandoraPidData are added in reco_sbnd.fcl.

Added sbnd_calorimetryalgdata and sbnd_gnewcalodata in calorimetry_sbnd.fcl.

Updated reco2_data.fcl to use pandoraCaloData and pandoraPidData.

## Checklist
- [ V ] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [ V ] Assigned at least 1 reviewer under `Reviewers`,
- [ V ] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Link(s) to docdb describing changes (optional)
SBN-doc-37574, used calibration constants from Run 14860

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
Hi Sungbin, was this PR intentionally setup to be merged into [feature/ebelchio12_wirecell_nfsp](https://github.com/SBNSoftware/sbndcode/tree/feature/ebelchio12_wirecell_nfsp) or was the intention to merge into `develop`?

**Review by linyan-w — APPROVED** [review]

**Comment by sungbinoh** [comment]
Hi Bear, this PR intentionally setup to be merged into [feature/ebelchio12_wirecell_nfsp](https://github.com/SBNSoftware/sbndcode/tree/feature/ebelchio12_wirecell_nfsp).

**Comment by linyan-w** [comment]
> Hi Bear, this PR intentionally setup to be merged into [feature/ebelchio12_wirecell_nfsp](https://github.com/SBNSoftware/sbndcode/tree/feature/ebelchio12_wirecell_nfsp).

Why is it? Are you thinking of a test with the feature branch, then another PR to merge the feature branch into develop?

**Comment by sungbinoh** [comment]
> > Hi Bear, this PR intentionally setup to be merged into [feature/ebelchio12_wirecell_nfsp](https://github.com/SBNSoftware/sbndcode/tree/feature/ebelchio12_wirecell_nfsp).
> 
> Why is it? Are you thinking of a test with the feature branch, then another PR to merge the feature branch into develop?

Yep. I was aware of that Tingjun was working on a PR to add pandoraShowerSBN in reco2_data.fcl into [feature/ebelchio12_wirecell_nfsp](https://github.com/SBNSoftware/sbndcode/tree/feature/ebelchio12_wirecell_nfsp).
Since we need to update the same fcl file, it would be better to make another PR after organizing "reco2_data.fcl" in this feature branch.

**Review by absolution1 — COMMENTED** [review]
Thanks @sungbinoh 
Once https://github.com/SBNSoftware/sbndcode/pull/512 is merged, could this PR be updated to address any merge conflict?  Then, this PR can be merged.

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by bear-is-asleep** [comment]
Hi @sungbinoh , can you resolve the conflicts between the two branches? At which point I can merge. Thanks!

**Comment by sungbinoh** [comment]
Hi @bear-is-asleep , I will do so after PR 512 is merged. Thanks!

**Comment by bear-is-asleep** [comment]
> Hi @bear-is-asleep , I will do so after PR 512 is merged. Thanks!

512 is merged, but I don't think this will change anything since that was compared to develop, and this is compared to a feature branch.

**Comment by sungbinoh** [comment]
I thought PR 512 was into [feature/ebelchio12_wirecell_nfsp](https://github.com/SBNSoftware/sbndcode/tree/feature/ebelchio12_wirecell_nfsp). I will prepare another PR into dev.

**Comment by sungbinoh** [comment]
@gputnam , Since initial data calibration constants are measured using modified box model, I want to keep for now.

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

**Comment by yangtj207** [comment]
What is the lifetime used in the calorimetry reconstruction?

**Comment by linyan-w** [comment]
> What is the lifetime used in the calorimetry reconstruction?

I don't see @sungbinoh modifying it in this PR (correct me if I didn't notice :D), so it should still be 10 ms. @annab101 is going to submit another PR to set it to 100 ms.

**Comment by sungbinoh** [comment]
Yeah, I think Linyan is correct.
(https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/Utilities/detectorproperties_sbnd.fcl#L8).

**Comment by bear-is-asleep** [comment]
Is this approved still @linyan-w ?

**Comment by linyan-w** [comment]
Yes. I approve this PR on its own from my perspective.

**Review by yangtj207 — APPROVED** [review]

**Review by absolution1 — APPROVED** [review]
Looks good.  This should be OK to merge now that Tingjun's PR is merged.

**Pull request merged**
