### PR TITLE
CRT Offline

### PR DESCRIPTION
**Pull request by henrylay97**
## Description 
This PR was made in 5 previous PRs all merged into this single branch. The updates are designed to integrate changes to the CRT reconstruction to run it on data. More details are available in each separate PR (#500 #501 #502 #503 #504)

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [x] Does this affect the standard workflow? 

### Relevant PR links (optional)
This PR should be merged into a release together with it's corresponding PRs in sbncode (SBNSoftware/sbncode#471) and sbnobj (SBNSoftware/sbnobj#113)

### Link(s) to docdb describing changes (optional)
CRT Data Reconstruction is detailed here: https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=36812

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 SBNSoftware/sbncode@56dc342f SBNSoftware/sbnobj@a4b93770 SBNSoftware/sbndcode@e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Review by bear-is-asleep — APPROVED** [review]

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02 https://github.com/SBNSoftware/sbndcode/commit/e303cbe2 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by henrylay97** [comment]
Hi @bear-is-asleep - sorry for the delay!

This is my summary of studying the changes listed in the regression tests for this PR (see [here](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15133&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)). This is mainly just for future reference for anyone looking back.

- **fcl_checks_sbndcode** these are all intended fcl changes that impact the standard workflow as detailed in the PR itself
- **nucosmics_caf_quick_test_sbndcode** && **single_caf_quick_test_sbndcode** the input files (reference reco2) were produced using a version of the CRT reco objects that could not fill the time fields in the same way. This is a direct result of the changes in the corresponding `sbncode` and `sbnobj`
- **nucosmics_detsim_quick_test_sbndcode** these are a direct result of the changes in commit 2854ced and are good
- **nucosmics_reco1_quick_test_sbndcode** these are changes to gaushit? And have nothing to do with this PR. I remember this cropping up earlier in the year, is it a known issue with the CI?

So this can be considered clean and be merged I think. Given the size of changes it is probably worth updating the reference files once this is merged.

**Comment by bear-is-asleep** [comment]
> Hi @bear-is-asleep - sorry for the delay!
> 
> This is my summary of studying the changes listed in the regression tests for this PR (see [here](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15133&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)). This is mainly just for future reference for anyone looking back.
> 
> * **fcl_checks_sbndcode** these are all intended fcl changes that impact the standard workflow as detailed in the PR itself
> * **nucosmics_caf_quick_test_sbndcode** && **single_caf_quick_test_sbndcode** the input files (reference reco2) were produced using a version of the CRT reco objects that could not fill the time fields in the same way. This is a direct result of the changes in the corresponding `sbncode` and `sbnobj`
> * **nucosmics_detsim_quick_test_sbndcode** these are a direct result of the changes in commit [2854ced](https://github.com/SBNSoftware/sbndcode/commit/2854cedc7ff1691aefb6c8cc5a2b04a4ffc6649b) and are good
> * **nucosmics_reco1_quick_test_sbndcode** these are changes to gaushit? And have nothing to do with this PR. I remember this cropping up earlier in the year, is it a known issue with the CI?
> 
> So this can be considered clean and be merged I think. Given the size of changes it is probably worth updating the reference files once this is merged.

Thanks Henry for the detailed response! For your last point, maybe this is a stochastic issue. Tom saw the same thing in his PR. I think it's small so we should be safe to proceed. 

We will have to wait for a new tagged version of `sbnobj` to merge this (otherwise it won't work).

**Comment by henrylay97** [comment]
Agree that it needs to be in the next release to pick up the sbnobj changes.

Given they've already been merged to sbnobj-develop then this could be merged now to make sure overnight builds are successful but that's your call.

**Pull request merged**
