### PR TITLE
Temporarily disable optical hybrid mode

### PR DESCRIPTION
**Pull request by fjnicolas**
This PR turns off optical simulation in the OUT-TPC volume (issue #219)

### CODE REVIEW

**Comment by pgreen135** [comment]
thanks @fjnicolas

**Comment by pgreen135** [comment]
trigger build

**Comment by etyley** [comment]
There are also some fcls that override the `simulate` list that will need updating (e.g. https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/JobConfigurations/standard/g4/g4_dirt_filter.fcl and presumably others in that directory)

**Review by marcodeltutto — CHANGES_REQUESTED** [review]
Thanks @fjnicolas! There are a few more fcls in `sbndcode/sbndcode/JobConfigurations/standard/` that still contain the `ionandscintout` and `pdfastsimout`. Can you please also comment them out?

**Review by marcodeltutto — APPROVED** [review]
Thanks @fjnicolas, looks good to me!

**Review by ggamezdiego — APPROVED** [review]

**Review by pgreen135 — APPROVED** [review]

**Pull request merged**
