### PR TITLE
PMT Decoder Ch Map Update

### PR DESCRIPTION
**Pull request by lynnt20**
Update Offline PMT Decoder channel mapping.

### CODE REVIEW

**Review by tomjunk — APPROVED** [review]
Looks good!

**Comment by lynnt20** [comment]
Thanks Tom!! 😄

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
SBND e26:prof build failed. This is due to a dependency issue from `sbncode` dependencies being mismatched. @ibsafa is this your impression and am I safe to merge?

**Comment by ibsafa** [comment]
@bear-is-asleep  c14 failure is known. e26 should pass, unless something changed that i am unaware of.

**Comment by fjnicolas** [comment]
@bear-is-asleep we probably need explicitly tell the CI to use the same LArSoft version sbncode (develop) is currently using, let's try this

**Comment by fjnicolas** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_90_00

**Comment by bear-is-asleep** [comment]
> @bear-is-asleep we probably need explicitly tell the CI to use the same LArSoft version sbncode (develop) is currently using, let's try this



> @bear-is-asleep we probably need explicitly tell the CI to use the same LArSoft version sbncode (develop) is currently using, let's try this

Ahhh thanks @fjnicolas !

**Pull request merged**
