### PR TITLE
[MCP2020A] Enable Flash Matching in Reconstruction

### PR DESCRIPTION
**Pull request by gputnam**
This pull request enables the Flash-Matching module to be run in SBND reconstruction.

It also updates CMake to properly build the sbndPDMapAlg as a tool (which appears to be intended, but is not the way it works currently).

### CODE REVIEW

**Comment by wesketchum** [comment]
Is this pending the changes in LArSoft/larsim#44 as well?

**Comment by gputnam** [comment]
No -- this turns on Iker's flash matching.

My understanding was that Marco's flash matching is not ready and is not going to be in the MC production.

**Comment by marcodeltutto** [comment]
Hi Gray, it is ready and there are two PRs (one in sbncode and one in sbndcode) which add the code and and enable it in the reco fcl file. This will have to go in the MC production as well.

**Comment by gputnam** [comment]
Ah, ok. In any case, this pull request is independent from that stuff.

**Pull request merged**
