### PR TITLE
Add SCE Correction Modules into Base Reco fcl-file and Add New Config Running SCE Corrections

### PR DESCRIPTION
**Pull request by gputnam**

### CODE REVIEW

**Comment by gputnam** [comment]
@etyley @absolution1 this adds in the configs for space charge correction reco. Ok to merge in?

**Comment by absolution1** [comment]
Hi @gputnam sorry for the delayed response.
The FCL changes/additions look OK to me, thanks for doing them!
Would you be able to rename and move the `standard_reco2_sbnd_sce.fcl` into the `reco` subdirectory and give it an appropriate name.  I'd prefer if we didn't have multiple 'standard' FCLs to avoid confusion.

**Comment by gputnam** [comment]
Makes sense! Done

**Comment by absolution1** [comment]
Thank you Gray.  One other small thing I just noticed, which might be a bit annoying, is that the data product labels (e.g. pandoraSCECalo`) have mixed upper and lower case whereas traditionally I think all product labels are lower case.  Could you make them lower case?  Then I am happy to approve

**Comment by gputnam** [comment]
Do you mean pandoraSCECalo -> pandorasceCalo or pandorascecalo? 

I think stuff like tracks are "pandoraTrack", not "pandoratrack"

**Comment by absolution1** [comment]
So they are!  The pandora labels are actually at odds with the rest of the labelling....
We should probably sort that out, but not now.  The SCE data product labels are all good.

**Review by absolution1 — APPROVED** [review]
Everything looks good.  Thanks for addressing the in-conversation comments.

**Pull request merged**
