### PR TITLE
Feature/rodrigoa detsim update

### PR DESCRIPTION
**Pull request by rodralva**
Updated version of det_sim. Added new HD Optical waveform tool it essentially:

- Creates an array of vectors (number of vectors is the number of the resolution increase in fhicl config of the tool
- For each photon, computes the correct shifted signal to use.

image

More details in docdbs [28150](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=28150), [29133](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=29133)

### CODE REVIEW

**Comment by rodralva** [comment]
trigger build

**Comment by rodralva** [comment]
image
image

Slight differences now noticiable in the raw and deconvolved wvfs, the shifts are within 1 bin distance, as spected.

**Comment by rodralva** [comment]
trigger build

**Review by fjnicolas — APPROVED** [review]
Thank you @rodralva! The PR looks good. Thank you for the plots comparing the old/new behaviour for the PMT raw/deco waveforms, there are some small shift as expected.

**Comment by fjnicolas** [comment]
CI changes unrrelated to this PR (LArsoft/larsim#110 and update to `genie_xsec v3_04_00`)

**Pull request merged**
