### PR TITLE
CRT Timing simulation improvement and changes for corresponding CRT timing reconstruction

### PR DESCRIPTION
**Pull request by Li-Jiaoyang97**
In this PR, I have changed the parameterisations for CRT timing simulation, mainly related to the time walk effect. The corresponding reconstruction for correcting such effect has also been made. More details will be seen in the SBND simulation meeting in April 5th. 

Moreover, related to Mean deposited charge for mips, I changed to 1.53 MeV instead of 1.75 MeV, as suggested in this plot here, the MIP energy deposition should be around 1.53 MeV. 
Screenshot 2024-04-04 at 16 50 41

### CODE REVIEW

**Comment by henrylay97** [comment]
Thanks @Li-Jiaoyang97 I'll come to today's meeting and then review after :smile:

**Review by henrylay97 — APPROVED** [review]
This looks good to go, nice work @Li-Jiaoyang97

**Review by marcodeltutto — APPROVED** [review]
Looks great! Thanks @Li-Jiaoyang97

**Comment by fjnicolas** [comment]
trigger build

**Comment by fjnicolas** [comment]
@Li-Jiaoyang97 I'm changing the base branch to SBN2024A (current production branch), I'll keep develop up to date in a future PR.

**Review by marcodeltutto — APPROVED** [review]
Thanks for catching this @Li-Jiaoyang97, looks good!

**Review by henrylay97 — APPROVED** [review]
Nice one catching it now :D

**Pull request merged**
