### PR TITLE
Accommodate breaking changes in geometry

### PR DESCRIPTION
**Pull request by knoepfel**
Pursuant to LArSoft/larcorealg#34.

### CODE REVIEW

**Comment by henrylay97** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_65_00 SBNSoftware/sbncode#322

**Comment by henrylay97** [comment]
trigger build LArSoft/larpandora#31 LArSoft/lar*@LARSOFT_SUITE_v09_65_00 SBNSoftware/sbncode#322

**Comment by henrylay97** [comment]
Okay so to cut a long story short-ish.

Testing this pull request highlighted some issues in larpandora some of which had been resolved by LArSoft/larpandora#31 the rest of which will be solved in LArSoft/larpandora#32.

Having dealt with these issues I have re-run the CI using the correct larsoft suite, the new sbncode release, this sbndcode PR _and_ the larpandora PR referenced above.

The results are available on the dashboard. This now passes the [unit tests](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/11065&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e20:prof) we were previously finding issues with. It also passes most of the [regressions tests](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/11065&platform=Linux%203.10.0-1160.81.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof).

The compilation test failure seems to be as a result of some geometry changes not picked up in the gallery area of sbndcode. These aren't noticed in compiling the full sbndcode only when this test is run is this cmake area executed. 

I am happy to approve this PR as is so that a release can proceed. There is the obvious issue that unless we wait for a larsoft patch then this release will be one where people cannot run SBND reconstruction without facing the issues mentioned in LArSoft/larpandora#30. That I leave as a decision for @fjnicolas and @miquelnebot. We could release it but make that caveat clear and follow it up soon with a genuine release?

I will follow it up with a pair of PRs that address the gallery issue and update the unit tests that were earlier failing to use a more modern configuration. Ideally these should be included in the v09_65_01 (or whatever the next ends up being) release.

**Comment by fjnicolas** [comment]
Thank you @henrylay97, this looks great! I'm not entirely convinced about publishing a release with the reconstruction not working properly. Given that the main changes/updates in the most recent LArSoft releases (`v09_65_*`) and sbncode `v09_65_01` are related to the geometry changes, I'm happy to wait for the LArSoft patch and then tag a fully working `sbndcode` release.

In the meantime, unless anyone has a different view, I'm happy to merge this PR into `develop` and update the dependencies so the CI starts getting back to work and PRs in the top-level repos can be tested again (though unit tests will keep failing until LArSoft/larpandora#32 gets in).

**Comment by henrylay97** [comment]
That sounds like a sensible plan to me! :) 

I agree we should start getting things into develop as it makes it easier for us to test other things (even if we have to specify larpandora #32 as you mentioned).

**Review by henrylay97 — APPROVED** [review]

**Pull request merged**
