### PR TITLE
updated hitdumper XA ophit label

### PR DESCRIPTION
**Pull request by rodralva**
As pointed out by @bear-is-asleep, [the HitDumper module](https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/Commissioning/fcls/hitdumpermodule.fcl#L15) was not loading properly the XArapuca Ophits produced by our deconvolution workflow. The ophits produced with deconvolved waveforms are called [ophitxarapuca](https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/JobConfigurations/base/reco_sbnd.fcl#L95) (notice the extra x).
This simple change should fix it.

### CODE REVIEW

**Comment by rodralva** [comment]
trigger build

**Review by bear-is-asleep — DISMISSED** [review]

**Comment by bear-is-asleep** [comment]
trigger build

**Comment by fjnicolas** [comment]
@bear-is-asleep CI is down until we migrate to the new compilers (we expect the new release this week). I'll trigger the CI tests once everything is back to normal.

**Comment by lynnt20** [comment]
FYI: we talked about this issue at the PDS Commissioning meeting yesterday. It seems like the labels are still inconsistent across the fcls. The file in this PR changes `ophitarapuca` -> `ophitxarapuca` in `hitdumper.fcl`, but in `run_hitdumper.fcl`, the label is still set as `ophitarapuca`. Maybe we should add a line in the module itself to specify which OpHit module label can't be found so debugging can be easier!

**Comment by bear-is-asleep** [comment]
Do we want to do deconvolution in `hitdumper`? I've found that many less hits and PE are found by the XAs using the current hitdumper configuration when compared to the deconvolved workflow (maybe a factor of 10) - https://github.com/SBNSoftware/sbndcode/blob/0fa2566c55afe3a834b9f8c32f6aa4f79a043eb8/sbndcode/JobConfigurations/base/reco_sbnd.fcl#L93-L100. @mstancar @lynnt20

**Comment by mstancar** [comment]
Hi Bear,
  I think the entire hitdumper concept is that it is different than standard reconstruction. It is faster and simpler even if the performance is less.  You can just run standard reconstruction if you want deconvolution, but deconvolution is unlikely to work without some data driven tuning once we have data .. . so not in the first few months

michelle


From: Bear Carlson ***@***.***>
Date: Thursday, November 9, 2023 at 10:21 AM
To: SBNSoftware/sbndcode ***@***.***>
Cc: Michelle D Stancari ***@***.***>, Mention ***@***.***>
Subject: Re: [SBNSoftware/sbndcode] updated hitdumper XA ophit label (PR #392)

Do we want to do deconvolution in hitdumper? I've found that many less hits and PE are found by the XAs using the current hitdumper configuration when compared to the deconvolved workflow (maybe a factor of 10) - https://github.com/SBNSoftware/sbndcode/blob/0fa2566c55afe3a834b9f8c32f6aa4f79a043eb8/sbndcode/JobConfigurations/base/reco_sbnd.fcl#L93-L100<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SBNSoftware_sbndcode_blob_0fa2566c55afe3a834b9f8c32f6aa4f79a043eb8_sbndcode_JobConfigurations_base_reco-5Fsbnd.fcl-23L93-2DL100&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=lt_NXZfi33b_FD7Pi8CxxlYkKBUZcYDxjKpS_vTRcto&e=>. @mstancar<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mstancar&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=7LZf8saL0blyWb5JpyDhAoRi24zwhDWqJ_NSwJNki-M&e=> @lynnt20<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lynnt20&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=lBI3FDBpLLDBXSz7EMoKMjoOGaoObSJwSmkv3CG_pOs&e=>

**Comment by bear-is-asleep** [comment]
> Hi Bear, I think the entire hitdumper concept is that it is different than standard reconstruction. It is faster and simpler even if the performance is less. You can just run standard reconstruction if you want deconvolution, but deconvolution is unlikely to work without some data driven tuning once we have data .. . so not in the first few months michelle From: Bear Carlson ***@***.***> Date: Thursday, November 9, 2023 at 10:21 AM To: SBNSoftware/sbndcode ***@***.***> Cc: Michelle D Stancari ***@***.***>, Mention ***@***.***> Subject: Re: [SBNSoftware/sbndcode] updated hitdumper XA ophit label (PR #392) Do we want to do deconvolution in hitdumper? I've found that many less hits and PE are found by the XAs using the current hitdumper configuration when compared to the deconvolved workflow (maybe a factor of 10) - https://github.com/SBNSoftware/sbndcode/blob/0fa2566c55afe3a834b9f8c32f6aa4f79a043eb8/sbndcode/JobConfigurations/base/reco_sbnd.fcl#L93-L100<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SBNSoftware_sbndcode_blob_0fa2566c55afe3a834b9f8c32f6aa4f79a043eb8_sbndcode_JobConfigurations_base_reco-5Fsbnd.fcl-23L93-2DL100&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=lt_NXZfi33b_FD7Pi8CxxlYkKBUZcYDxjKpS_vTRcto&e=>. @mstancar<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mstancar&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=7LZf8saL0blyWb5JpyDhAoRi24zwhDWqJ_NSwJNki-M&e=> @lynnt20<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_lynnt20&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=lBI3FDBpLLDBXSz7EMoKMjoOGaoObSJwSmkv3CG_pOs&e=> — Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SBNSoftware_sbndcode_pull_392-23issuecomment-2D1804143828&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=VkXMJRj86e6K6PzDLP-qhg2b2ZL9Vj4nutM6V8-s52U&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_APOZIQGHMTIWV3BDC4ZRVEDYDT7IPAVCNFSM6AAAAAA6D72JK2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBUGE2DGOBSHA&d=DwMFaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=XwT4z_xoYuahpWzd6VjM1ZO21Bag6v9xST-R_JW6GZM&m=5erFFX0nzyel-RhsjnXLqSoqeDemM0d6rEUCsEceG3KNo7eTKCJFzdZPJKsrP_sV&s=Zp58tqjnsryJqWgMWXjGJqX194YfPQ9RTu3meEjldTQ&e=>. You are receiving this because you were mentioned.Message ID: ***@***.***>

Thanks Michelle! Lauren had the same sentiment. @fjnicolas said the non deconvolution parameters for the PMTs have been tuned, vs. little to no tuning for the XAs. This causes a drastic underestimation in XA hits found, so this may be something we should address if we want to use XAs in the hitdumper.

**Comment by fjnicolas** [comment]
trigger build

**Comment by bear-is-asleep** [comment]
@rodralva we gotta remove the lines at the end of `run_hitdumper.fcl` before merging these changes

**Comment by bear-is-asleep** [comment]
> @rodralva we gotta remove the lines at the end of `run_hitdumper.fcl` before merging these changes

i'm sorry i didn't know those snuck into my PR

**Review by bear-is-asleep — APPROVED** [review]

**Comment by fjnicolas** [comment]
trigger build

**Pull request merged**
