### PR TITLE
OM event display

### PR DESCRIPTION
**Pull request by yangtj207**
Add a module to make event displays. This can be potentially used by OM and other commissioning studies. 

Here is one example:
sbnd_run12007_event678_tpc0_plane0

### CODE REVIEW

**Comment by tomjunk** [comment]
Looks okay, though it looks like this PR swept in the commits from PR 441.   Maybe the same branch was used for both PRs?

**Comment by fjnicolas** [comment]
> Looks okay, though it looks like this PR swept in the commits from PR 441. Maybe the same branch was used for both PRs?

I'll rebase this after merging #411 to isolate the specific changes intended by this PR

**Comment by yangtj207** [comment]
Thank you. Yes, 441 and 443 are based on the same branch. I will try to using separate branches for different PR in the future.

**Comment by fjnicolas** [comment]
trigger build

**Comment by fjnicolas** [comment]
CI failures unrrelated to the PR

**Pull request merged**
