### PR TITLE
Filter to reject events with very high hit multiplicity (ported from ProtoDUNE)

### PR DESCRIPTION
**Pull request by absolution1**
## Description 
Include a port of the ProtoDUNE hit filter to reject events with a very high hit multiplicity.  In data, some events have a very large number of hits: these events demand a lot of memory/processing time and are unusable.  The filter is connected up to the data workflow to reject such events after gaushit, saving on memory and processing time.

I have set the minimum number of hits per TPC to be 50,000.  This can obviously be iterated on as the filter is deployed.

I've included an extra data processing fcl (`reco1_data_storefilteredevents.fcl`) that keeps the filtered events (but in a separate output file)

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [ ] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [ ] Does this affect the standard workflow?

### CODE REVIEW

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Review by bear-is-asleep — APPROVED** [review]
Looks good! Do we want to do this for MC?

**Comment by absolution1** [comment]
> Looks good! Do we want to do this for MC?

Sorry @bear-is-asleep I completely missed this.
I don't think we do, for now at least.  The filter is to reduce the number of times we get stuck in a long processing with data.  The filter is quite generous in terms of letting events through, so I think the data/MC bias should be small.

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
Hi @absolution1 , can you resolve conflicts and update to develop? This should fix the CI build issue. Thanks!

**Comment by bear-is-asleep** [comment]
@absolution1 , can you resolve conflicts and update the branch to develop? There are some build errors which I think are attributed to not being on the develop branch.

**Comment by absolution1** [comment]
@bear-is-asleep this is done.
@henrylay97 can you check that the CRT bits in reco1_data.fcl are still OK?

**Comment by henrylay97** [comment]
YAY! :partying_face: (CRT stuff is all good (services & producer))

**Comment by bear-is-asleep** [comment]
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

**Comment by bear-is-asleep** [comment]
Ready to merge

**Pull request merged**
