### PR TITLE
Add fcl testing framework based on icarus fcl testing framework.

### PR DESCRIPTION
**Pull request by hgreenlee**
Add unit test for testing fcl files similar as the one in icaruscode.

### CODE REVIEW

**Comment by hgreenlee** [comment]
Duplicate of PR 273

**Comment by pgreen135** [comment]
Re-opening this, instead of https://github.com/SBNSoftware/sbndcode/pull/273 as compatible with merging into develop

**Review by henrylay97 — APPROVED** [review]
This looks good to me. Its a useful extra arrow to our quiver and is different & complementary to my set of tests. 

My only extra point is that I would suggest that you make a github issue in sbndcode to track the removal / fixing / archiving of the files listed in `SkipTesting.txt`

**Comment by pgreen135** [comment]
Thanks @henrylay97, making an issue to keep track of this is a good idea. How does this test integrate with the existing ones? Is this to be run as part of the unit/CI tests?

**Comment by pgreen135** [comment]
great! thanks for the explanation, I will get this merged into the next release

**Pull request merged**
