### PR TITLE
created CRT artdaq fragment producer for simulated events

### PR DESCRIPTION
**Pull request by eyandel**

### CODE REVIEW

**Review by marcodeltutto — APPROVED** [review]
Looks great!

**Comment by fjnicolas** [comment]
trigger build

**Comment by fjnicolas** [comment]
Hi @eyandel, I think there is a missing header in the CRTArtdaqFragmentProducer.fcl, could you fix this? Thanks!

**Review by mstancar — APPROVED** [review]

**Comment by fjnicolas** [comment]
Hi @eyandel, there is still a missing header (`crtsimmodules_sbnd.fcl`) for the `@local::sbnd_crtsim.DetSimParams.ClockSpeedCRT` . Can you push the the changes? Thank you!

**Comment by fjnicolas** [comment]
trigger build

**Pull request merged**
